name: Publish iOS OTA preview

on:
  workflow_dispatch: {}

jobs:
  publish_preview:
    name: Publish iOS preview update
    type: update
    environment: preview
    env:
      EAS_NO_VCS: "1"
    params:
      platform: ios
      channel: preview
      message: "manual iOS OTA preview"
