import { StyleSheet, type TextStyle } from 'react-native';
import { colors, spacing, radii, shadows } from '@/constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bgPrimary },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  btn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  dateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: spacing.sm,
    gap: 16,
  },
  dateBtn: { padding: 4 },
  content: { padding: spacing.md, paddingBottom: spacing.xl },
  loading: { paddingVertical: 60, alignItems: 'center' },
  summary: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  sumTile: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: radii.md,
    padding: spacing.sm,
    alignItems: 'center',
    ...shadows.subtle,
  },
  chartCard: {
    backgroundColor: '#fff',
    borderRadius: radii.md,
    padding: spacing.sm,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xs,
    marginBottom: 4,
  },
  overlayBtns: { flexDirection: 'row', gap: 4 },
  overlayBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#F3F4F6',
  },
  overlayBtnActive: { backgroundColor: colors.brand },
  actionCard: {
    backgroundColor: '#ECFDF5',
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
    gap: spacing.sm,
  },
  askCard: {
    backgroundColor: '#FFF7ED',
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: '#F97316',
  },
  askItem: {
    marginTop: 10, paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#FED7AA',
  },
  askBtnRow: { flexDirection: 'row', gap: 8, marginTop: 8, justifyContent: 'flex-end' },
  askChip: {
    paddingHorizontal: 14, paddingVertical: 6,
    borderRadius: radii.full, backgroundColor: '#fff',
    borderWidth: 1, borderColor: '#F97316',
  },
  askChipPrimary: { backgroundColor: '#F97316', borderColor: '#F97316' },
  findingCard: {
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderLeftWidth: 3,
  },
  findingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  noFindings: {
    alignItems: 'center',
    paddingVertical: 40,
  },
});

export const txt = {
  title: { fontSize: 17, fontWeight: '600', color: colors.labelPrimary } as TextStyle,
  dateLabel: { fontSize: 16, fontWeight: '500', color: colors.labelPrimary } as TextStyle,
  sectionTitle: { fontSize: 15, fontWeight: '600', color: colors.labelPrimary } as TextStyle,
  askTitle: { fontSize: 15, fontWeight: '600', color: '#9A3412' } as TextStyle,
  askSub: { fontSize: 12, color: '#9A3412', marginTop: 4 } as TextStyle,
  askText: { fontSize: 13, color: '#7C2D12', lineHeight: 19 } as TextStyle,
  askChipPrimary: { fontSize: 13, fontWeight: '600', color: '#fff' } as TextStyle,
  askChipSecondary: { fontSize: 13, fontWeight: '600', color: '#F97316' } as TextStyle,
  body: { fontSize: 14, color: colors.labelPrimary } as TextStyle,
  caption: { fontSize: 12, color: colors.labelSecondary } as TextStyle,
  sumLabel: { fontSize: 11, color: colors.labelSecondary, marginBottom: 4 } as TextStyle,
  sumValue: { fontSize: 20, fontWeight: '700' } as TextStyle,
  sumSub: { fontSize: 11, fontWeight: '400', color: colors.labelSecondary } as TextStyle,
  findingSubject: { fontSize: 14, fontWeight: '600', flex: 1 } as TextStyle,
  confidence: { fontSize: 10, color: colors.labelSecondary } as TextStyle,
  hypothesis: { fontSize: 13, color: colors.labelPrimary, marginTop: 4, lineHeight: 19 } as TextStyle,
  action: { fontSize: 13, fontWeight: '500', marginTop: 8, lineHeight: 19 } as TextStyle,
  overlayBtn: { fontSize: 11, color: colors.labelSecondary } as TextStyle,
  overlayBtnActive: { color: '#fff', fontWeight: '600' } as TextStyle,
};
