import { StyleSheet, type TextStyle } from 'react-native';
import { spacing, radii, shadows } from '../constants/theme';
import type { ColorPalette } from '../hooks/useTheme';

export const createStyles = (c: ColorPalette) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: c.bgPrimary },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  btn: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  dateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: spacing.sm,
    gap: 16,
  },
  dateBtn: { padding: 4 },
  content: { padding: spacing.md, paddingBottom: spacing.xl },
  loading: { paddingVertical: 60, alignItems: 'center' },
  summary: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  sumTile: {
    flex: 1,
    backgroundColor: c.bgCard,
    borderRadius: radii.md,
    padding: spacing.sm,
    alignItems: 'center',
    ...shadows.subtle,
  },
  chartCard: {
    backgroundColor: c.bgCard,
    borderRadius: radii.md,
    padding: spacing.sm,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.xs,
    marginBottom: 4,
  },
  overlayBtns: { flexDirection: 'row', gap: 4 },
  overlayBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: c.fill,
  },
  overlayBtnActive: { backgroundColor: c.brand },
  actionCard: {
    backgroundColor: c.tintGreen,
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: c.green,
    gap: spacing.sm,
  },
  askCard: {
    backgroundColor: c.tintOrange,
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderLeftWidth: 3,
    borderLeftColor: c.orange,
  },
  askItem: {
    marginTop: 10, paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: c.separator,
  },
  askBtnRow: { flexDirection: 'row', gap: 8, marginTop: 8, justifyContent: 'flex-end' },
  askChip: {
    paddingHorizontal: 14, paddingVertical: 6,
    borderRadius: radii.full, backgroundColor: c.bgCard,
    borderWidth: 1, borderColor: c.orange,
  },
  askChipPrimary: { backgroundColor: c.orange, borderColor: c.orange },
  findingCard: {
    borderRadius: radii.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderLeftWidth: 3,
  },
  findingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  noFindings: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  agentLink: {
    marginBottom: spacing.md,
  },
});

export const createTxt = (c: ColorPalette) => ({
  title: { fontSize: 17, fontWeight: '600', color: c.labelPrimary } as TextStyle,
  dateLabel: { fontSize: 16, fontWeight: '500', color: c.labelPrimary } as TextStyle,
  sectionTitle: { fontSize: 15, fontWeight: '600', color: c.labelPrimary } as TextStyle,
  askTitle: { fontSize: 15, fontWeight: '600', color: c.orange } as TextStyle,
  askSub: { fontSize: 12, color: c.orange, marginTop: 4 } as TextStyle,
  askText: { fontSize: 13, color: c.labelPrimary, lineHeight: 19 } as TextStyle,
  askChipPrimary: { fontSize: 13, fontWeight: '600', color: '#fff' } as TextStyle,
  askChipSecondary: { fontSize: 13, fontWeight: '600', color: c.orange } as TextStyle,
  body: { fontSize: 14, color: c.labelPrimary } as TextStyle,
  caption: { fontSize: 12, color: c.labelSecondary } as TextStyle,
  sumLabel: { fontSize: 11, color: c.labelSecondary, marginBottom: 4 } as TextStyle,
  sumValue: { fontSize: 20, fontWeight: '700', color: c.labelPrimary } as TextStyle,
  sumSub: { fontSize: 11, fontWeight: '400', color: c.labelSecondary } as TextStyle,
  findingSubject: { fontSize: 14, fontWeight: '600', flex: 1, color: c.labelPrimary } as TextStyle,
  confidence: { fontSize: 10, color: c.labelSecondary } as TextStyle,
  hypothesis: { fontSize: 13, color: c.labelPrimary, marginTop: 4, lineHeight: 19 } as TextStyle,
  action: { fontSize: 13, fontWeight: '500', marginTop: 8, lineHeight: 19, color: c.labelPrimary } as TextStyle,
  overlayBtn: { fontSize: 11, color: c.labelSecondary } as TextStyle,
  overlayBtnActive: { color: '#fff', fontWeight: '600' } as TextStyle,
});
