-- 补剂产品库初始数据（基于用户实际使用的产品）
INSERT INTO supplement_products (name, brand, category, description, serving_size, servings_per_container, container_count, ingredients, price_cny, price_per_serving, purchase_url, platform, certifications, capsule_type, usage_advice, precautions, gene_relevance, health_tags, rating, review_count) VALUES

-- 1. Thorne Basic B Complex
('Basic B Complex', 'Thorne', 'vitamin',
 '含酶活性B族维生素复合物，使用Quatrefolic®专利活性叶酸。NSF for Sport认证，运动员安全。',
 '1 Capsule', 60, 60,
 '[{"name":"Thiamin (B1)","form":"Thiamine HCl","amount":"110mg","daily_value_pct":9167},
   {"name":"Riboflavin (B2)","form":"Riboflavin 5''-Phosphate Sodium","amount":"10mg","daily_value_pct":769},
   {"name":"Niacin (B3)","form":"Niacinamide 130mg + Niacin 10mg","amount":"140mg","daily_value_pct":875},
   {"name":"Vitamin B6","form":"Pyridoxal 5''-Phosphate (P-5-P)","amount":"10mg","daily_value_pct":588},
   {"name":"Folate","form":"L-5-Methyltetrahydrofolate (Quatrefolic®)","amount":"667mcg DFE","daily_value_pct":167},
   {"name":"Vitamin B12","form":"Methylcobalamin","amount":"400mcg","daily_value_pct":16667},
   {"name":"Biotin","form":"Biotin","amount":"400mcg","daily_value_pct":1333},
   {"name":"Pantothenic Acid (B5)","form":"Calcium Pantothenate","amount":"110mg","daily_value_pct":2200},
   {"name":"Choline","form":"Choline Citrate","amount":"28mg","daily_value_pct":5}]'::jsonb,
 190.41, 3.17,
 'https://cn.iherb.com/pr/thorne-basic-b-complex-60-capsules/18791', 'iherb',
 '["NSF for Sport","Gluten Free"]'::jsonb, 'vegetarian',
 '每日1粒，随餐服用。B6仅10mg，长期服用安全无忧。',
 'B3含少量烟酸(10mg)，极少数人可能有轻微潮红。',
 '[{"gene":"MTHFR","genotype":"CT/TT","relevance":"使用Quatrefolic®专利活性叶酸，MTHFR突变者首选"}]'::jsonb,
 '["B族维生素","能量代谢","甲基化","神经健康"]'::jsonb,
 4.8, 22052),

-- 2. Life Extension BioActive Complete B-Complex
('BioActive Complete B-Complex', 'Life Extension', 'vitamin',
 '含酶活性B族维生素，高剂量B5(500mg)和B2(75mg)，适合压力大或口腔溃疡时期。',
 '2 Vegetarian Capsules', 30, 60,
 '[{"name":"Thiamin (B1)","form":"Thiamine HCl","amount":"100mg","daily_value_pct":8333},
   {"name":"Riboflavin (B2)","form":"Riboflavin + Riboflavin 5''-Phosphate","amount":"75mg","daily_value_pct":5769},
   {"name":"Niacin (B3)","form":"Niacinamide + Niacin","amount":"100mg","daily_value_pct":625},
   {"name":"Vitamin B6","form":"Pyridoxine HCl + Pyridoxal 5''-Phosphate","amount":"100mg","daily_value_pct":5882},
   {"name":"Folate","form":"L-5-Methyltetrahydrofolate","amount":"680mcg DFE","daily_value_pct":170},
   {"name":"Vitamin B12","form":"Methylcobalamin","amount":"300mcg","daily_value_pct":12500},
   {"name":"Biotin","form":"Biotin","amount":"1000mcg","daily_value_pct":3333},
   {"name":"Pantothenic Acid (B5)","form":"D-Calcium Pantothenate","amount":"500mg","daily_value_pct":10000},
   {"name":"Calcium","form":"D-Calcium Pantothenate + Dicalcium Phosphate","amount":"50mg","daily_value_pct":4},
   {"name":"Inositol","form":"Inositol","amount":"100mg","daily_value_pct":null},
   {"name":"PABA","form":"para-Aminobenzoic Acid","amount":"50mg","daily_value_pct":null}]'::jsonb,
 77.18, 2.57,
 'https://cn.iherb.com/pr/life-extension-bioactive-complete-b-complex-60-vegetarian-capsules/67051', 'iherb',
 '["Non-GMO"]'::jsonb, 'vegetarian',
 '每日2粒，随餐服用。B6含量100mg较高，不建议长期超过6个月连续使用。',
 'B6剂量100mg接近安全上限，长期使用需注意周围神经症状。B5剂量极高(500mg)可能引起轻微胃不适。',
 '[{"gene":"MTHFR","genotype":"CT/TT","relevance":"含活性叶酸5-MTHF，适合MTHFR突变者"}]'::jsonb,
 '["B族维生素","能量代谢","压力管理","口腔溃疡"]'::jsonb,
 4.8, 106826),

-- 3. Life Extension TMG 500mg
('TMG 500mg', 'Life Extension', 'amino',
 '三甲基甘氨酸(甜菜碱无水物)，支持健康的同型半胱氨酸水平，促进甲基化循环。',
 '2 Liquid Vegetarian Capsules', 30, 60,
 '[{"name":"Trimethylglycine (TMG)","form":"Betaine Anhydrous","amount":"1000mg","daily_value_pct":null}]'::jsonb,
 72.20, 2.41,
 'https://cn.iherb.com/pr/life-extension-tmg-500-mg-60-liquid-vegetarian-capsules/55665', 'iherb',
 '["Non-GMO","Gluten Free"]'::jsonb, 'liquid',
 '每日2粒，随餐服用。与B族维生素搭配效果更佳，共同支持甲基化循环。',
 '高剂量可能引起胃肠不适，建议从低剂量开始。',
 '[{"gene":"MTHFR","genotype":"CT/TT","relevance":"TMG作为甲基供体，帮助MTHFR突变者维持甲基化"},
   {"gene":"BHMT","genotype":"all","relevance":"TMG通过BHMT途径提供替代甲基化路径"}]'::jsonb,
 '["甲基化","同型半胱氨酸","肝脏健康","心血管"]'::jsonb,
 4.8, 6761),

-- 4. Jarrow Formulas B-Right
('B-Right Optimized B-Complex', 'Jarrow Formulas', 'vitamin',
 '优化B族复合物，100粒大包装性价比高。含Quatrefolic®叶酸和P-5-P活性B6。',
 '1 Veggie Capsule', 100, 100,
 '[{"name":"Thiamin (B1)","form":"Thiamine HCl","amount":"25mg","daily_value_pct":2083},
   {"name":"Riboflavin (B2)","form":"Riboflavin","amount":"25mg","daily_value_pct":1923},
   {"name":"Niacin (B3)","form":"Niacinamide","amount":"25mg","daily_value_pct":156},
   {"name":"Vitamin B6","form":"Pyridoxine HCl + P-5-P","amount":"25mg","daily_value_pct":1471},
   {"name":"Folate","form":"Quatrefolic® (6S)-5-MTHF","amount":"400mcg DFE","daily_value_pct":100},
   {"name":"Vitamin B12","form":"Methylcobalamin","amount":"100mcg","daily_value_pct":4167},
   {"name":"Biotin","form":"Biotin","amount":"100mcg","daily_value_pct":333},
   {"name":"Pantothenic Acid (B5)","form":"D-Calcium Pantothenate","amount":"50mg","daily_value_pct":1000},
   {"name":"Choline","form":"Choline Bitartrate","amount":"25mg","daily_value_pct":5},
   {"name":"Inositol","form":"Inositol","amount":"25mg","daily_value_pct":null},
   {"name":"PABA","form":"para-Aminobenzoic Acid","amount":"10mg","daily_value_pct":null}]'::jsonb,
 215.37, 2.15,
 'https://cn.iherb.com/pr/jarrow-formulas-b-right-100-veggie-caps/68'||'0', 'iherb',
 '["Non-GMO","Gluten Free","Vegan"]'::jsonb, 'vegetarian',
 '每日1粒，随餐服用。中等剂量，适合日常维持。',
 '无明显风险，剂量温和。',
 '[{"gene":"MTHFR","genotype":"CT/TT","relevance":"含Quatrefolic®活性叶酸"}]'::jsonb,
 '["B族维生素","日常维持","性价比"]'::jsonb,
 4.8, 8519),

-- 5. Doctor's Best Ubiquinol 50mg
('Ubiquinol with Kaneka Q+', 'Doctor''s Best', 'antioxidant',
 '还原型辅酶Q10(泛醇)，Kaneka Q+®原料。生物利用度高于普通CoQ10(泛醌)。',
 '1 Softgel', 90, 90,
 '[{"name":"Ubiquinol (CoQ10)","form":"Kaneka Q+® Reduced Form","amount":"50mg","daily_value_pct":null}]'::jsonb,
 313.51, 3.48,
 'https://cn.iherb.com/pr/doctor-s-best-ubiquinol-with-kaneka-50-mg-90-softgels/36'||'019', 'iherb',
 '["Non-GMO"]'::jsonb, 'softgel',
 '每日1粒，随含脂肪餐服用（脂溶性，需要脂肪辅助吸收）。',
 '服用他汀类药物者应补充CoQ10，因他汀会降低体内CoQ10水平。',
 '[]'::jsonb,
 '["心血管","抗氧化","线粒体","能量代谢","他汀搭配"]'::jsonb,
 4.7, 2398),

-- 6. Sports Research Alaskan Omega-3
('Alaskan Omega-3 Fish Oil Triple Strength', 'Sports Research', 'other',
 '阿拉斯加野生鱼油，Triple Strength高浓度。MSC可持续渔业认证。每粒1250mg鱼油含1040mg Omega-3。',
 '1 Softgel', 90, 90,
 '[{"name":"Fish Oil","form":"Alaska Pollock Oil","amount":"1250mg","daily_value_pct":null},
   {"name":"Total Omega-3","form":"","amount":"1040mg","daily_value_pct":null},
   {"name":"EPA","form":"Eicosapentaenoic Acid","amount":"600mg","daily_value_pct":null},
   {"name":"DHA","form":"Docosahexaenoic Acid","amount":"400mg","daily_value_pct":null}]'::jsonb,
 265.18, 2.95,
 'https://cn.iherb.com/pr/sports-research-omega-3-fish-oil-triple-strength-90-softgels/100'||'574', 'iherb',
 '["Non-GMO","Gluten Free","MSC Certified"]'::jsonb, 'softgel',
 '每日1粒，随餐服用。冷藏保存可延长保质期并减少鱼腥味。',
 '手术前2周停用（可能影响凝血）。服用抗凝药物者需咨询医生。',
 '[]'::jsonb,
 '["心血管","抗炎","大脑健康","关节","鱼油"]'::jsonb,
 4.8, 46586),

-- 7. NOW Foods Melatonin 3mg
('Melatonin 3mg', 'NOW Foods', 'other',
 '褪黑荷尔蒙，支持健康睡眠周期。素食胶囊，不含常见过敏原。',
 '1 Veg Capsule', 60, 60,
 '[{"name":"Melatonin","form":"Melatonin","amount":"3mg","daily_value_pct":null}]'::jsonb,
 37.54, 0.63,
 'https://cn.iherb.com/pr/now-foods-melatonin-3-mg-60-veg-capsules/14'||'810', 'iherb',
 '["Non-GMO","Vegan","Kosher"]'::jsonb, 'vegetarian',
 '睡前30分钟服用1粒。短期使用安全，长期使用建议间歇服用（用5天停2天）。',
 '可能引起白天嗜睡，驾驶前避免服用。不建议与镇静类药物同用。孕妇禁用。',
 '[]'::jsonb,
 '["睡眠","时差调节","抗氧化"]'::jsonb,
 4.7, 58806),

-- 8. California Gold Nutrition CoQ10 with PQQ
('CoQ10 with PQQ', 'California Gold Nutrition', 'antioxidant',
 '辅酶Q10(泛醌USP)100mg + PQQ 10mg复合配方。含向日葵卵磷脂提高吸收率。iTested第三方检测。',
 '1 Veggie Softgel', 60, 60,
 '[{"name":"Coenzyme Q10","form":"Ubiquinone USP","amount":"100mg","daily_value_pct":null},
   {"name":"PQQ (Pyrroloquinoline Quinone)","form":"PQQ Disodium Salt","amount":"10mg","daily_value_pct":null}]'::jsonb,
 135.81, 2.26,
 'https://cn.iherb.com/pr/california-gold-nutrition-coq10-with-pqq-100-mg-60-veggie-softgels/88'||'816', 'iherb',
 '["Non-GMO","Gluten Free","iTested"]'::jsonb, 'softgel',
 '每日1粒，随含脂肪餐服用。CoQ10+PQQ协同支持线粒体功能。',
 '泛醌(Ubiquinone)需要体内转化为泛醇(Ubiquinol)，40岁以上转化效率下降，可考虑直接补充泛醇。',
 '[]'::jsonb,
 '["心血管","抗氧化","线粒体","大脑健康","PQQ"]'::jsonb,
 4.8, 6830)

ON CONFLICT DO NOTHING;
