import React from 'react';
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { getLifeWorkspace, saveLifeWorkspace } from '@/services/lifeNavigation';
import { addDays, blankData, blankTask, blankWeek, localDate, mondayOf } from './model';
import LifeNavigationWorkspace from './LifeNavigationWorkspace';
vi.mock('@/contexts/AuthContext', () => ({ useAuth: () => ({ user: { id: 7 }, isAuthenticated: true }) }));
vi.mock('@/services/lifeNavigation', () => ({ getLifeWorkspace: vi.fn(), saveLifeWorkspace: vi.fn(), getLifeHistory: vi.fn().mockResolvedValue([]) }));
const today = localDate();
const monday = mondayOf(today);
const makeWorkspace = () => ({ schema_version: 'life_navigation.v1' as const, revision: 3, data: blankData(), updated_at: null });
describe('Life navigation reference workspace interaction', () => {
    beforeEach(() => { vi.clearAllMocks(); vi.mocked(getLifeWorkspace).mockResolvedValue(makeWorkspace()); });
    afterEach(cleanup);
    it('offers a home logo and all eight views through a collapsible navigation', async () => {
        render(<LifeNavigationWorkspace />);
        const home = await screen.findByRole('link', { name: 'Reva 首页' });
        expect(home).toHaveAttribute('href', '/');
        const menu = screen.getByRole('button', { name: '展开导航' });
        expect(menu).toHaveAttribute('aria-expanded', 'false');
        fireEvent.click(menu);
        expect(menu).toHaveAttribute('aria-expanded', 'true');
        const nav = screen.getByRole('navigation', { name: '人生导航视图' });
        for (const name of ['今日', '周计划', '时段导航', '周复盘', '成果', '方向与季度', '机会', '备份']) expect(within(nav).getByRole('button', { name })).toBeTruthy();
        fireEvent.click(within(nav).getByRole('button', { name: '机会' }));
        expect(screen.getByRole('button', { name: '展开导航' })).toHaveAttribute('aria-expanded', 'false');
        expect(screen.getByRole('button', { name: '保存工作区' })).toBeTruthy();
    });
    it('moves across weeks and days while keeping draft data without creating or saving weeks', async () => {
        render(<LifeNavigationWorkspace />);
        await screen.findByText('添加主任务');
        fireEvent.click(screen.getByText('添加主任务'));
        fireEvent.change(screen.getByLabelText('任务标题'), { target: { value: 'Keep my draft' } });
        fireEvent.click(screen.getByRole('button', { name: '下一周' }));
        expect(screen.getByLabelText('查看日期')).toHaveValue(addDays(today, 7));
        expect(screen.queryByLabelText('任务标题')).toBeNull();
        fireEvent.click(screen.getByRole('button', { name: '上一周' }));
        expect(screen.getByLabelText('任务标题')).toHaveValue('Keep my draft');
        fireEvent.click(screen.getByRole('button', { name: `${monday} 周一` }));
        expect(screen.getByLabelText('查看日期')).toHaveValue(monday);
        fireEvent.click(screen.getByRole('button', { name: '回到今天' }));
        expect(screen.getByLabelText('查看日期')).toHaveValue(today);
        expect(saveLifeWorkspace).not.toHaveBeenCalled();
        expect(getLifeWorkspace).toHaveBeenCalledTimes(1);
    });
    it('creates a task in the selected weekly slot and opens its editable card without saving', async () => {
        render(<LifeNavigationWorkspace />);
        fireEvent.click(await screen.findByText('周计划'));
        fireEvent.click(screen.getByRole('button', { name: `${monday} 下午添加事项` }));
        expect(screen.getByLabelText('查看日期')).toHaveValue(monday);
        expect(screen.getByLabelText('计划时段')).toHaveValue('afternoon');
        expect(document.activeElement).toBe(screen.getByLabelText('任务标题').closest('section'));
        expect(saveLifeWorkspace).not.toHaveBeenCalled();
    });
    it('derives focus, completion and all four time slots from the editable tasks', async () => {
        const workspace = makeWorkspace();
        const week = blankWeek();
        const main = { ...blankTask(today, 'main'), title: 'Write the plan', slot: 'morning' as const };
        week.tasks = [main, { ...blankTask(today, 'auxiliary'), title: 'Review it', slot: 'evening', status: 'done' }];
        workspace.data.weeks[monday] = week;
        vi.mocked(getLifeWorkspace).mockResolvedValue(workspace);
        render(<LifeNavigationWorkspace />);
        const schedule = await screen.findByRole('region', { name: '今日时间安排' });
        expect(screen.getByText('已完成 1 / 2 项')).toBeTruthy();
        for (const slot of ['上午', '下午', '晚上', '灵活']) expect(within(schedule).getByRole('heading', { name: slot })).toBeTruthy();
        fireEvent.click(within(schedule).getByRole('button', { name: '编辑任务：Write the plan' }));
        expect(document.activeElement).toBe(screen.getAllByLabelText('任务标题')[0].closest('section'));
        fireEvent.change(screen.getAllByLabelText('任务标题')[0], { target: { value: 'Updated plan' } });
        expect(within(schedule).getByRole('button', { name: '编辑任务：Updated plan' })).toBeTruthy();
        fireEvent.change(screen.getAllByLabelText('计划时段')[0], { target: { value: 'afternoon' } });
        expect(within(within(schedule).getByRole('heading', { name: '下午' }).closest('section')!).getByRole('button', { name: '编辑任务：Updated plan' })).toBeTruthy();
        for (const name of ['今日任务', '时间安排', '日记录']) expect(screen.getByRole('link', { name })).toHaveAttribute('href');
        expect(saveLifeWorkspace).not.toHaveBeenCalled();
    });
});
