import React from 'react';
import { fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { getLifeWorkspace, saveLifeWorkspace, getLifeHistory, getLifeBackup, importLifeBackup, restoreLifeWorkspace } from '@/services/lifeNavigation';
import { blankData } from './model';
let user = { id: 7 };
vi.mock('@/contexts/AuthContext', () => ({ useAuth: () => ({ user, isAuthenticated: true }) }));
vi.mock('@/services/lifeNavigation', () => ({ getLifeWorkspace: vi.fn(), saveLifeWorkspace: vi.fn(), getLifeHistory: vi.fn().mockResolvedValue([]), getLifeBackup: vi.fn(), importLifeBackup: vi.fn(), restoreLifeWorkspace: vi.fn() }));
import LifeNavigationWorkspace from './LifeNavigationWorkspace';
const workspace = { schema_version: 'life_navigation.v1' as const, revision: 3, data: blankData(), updated_at: '2026-10-10T00:00:00Z' };
describe('Life navigation saved state and account isolation', () => {
    afterEach(cleanup);
    beforeEach(() => { vi.clearAllMocks(); user = { id: 7 }; (getLifeWorkspace as ReturnType<typeof vi.fn>).mockResolvedValue(workspace); });
    it('keeps local edits on conflict and does not claim saved', async () => {
        (saveLifeWorkspace as ReturnType<typeof vi.fn>).mockRejectedValue({ response: { status: 409 } });
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('方向与季度'));
        fireEvent.click(screen.getByText('方向与季度'));
        fireEvent.change(screen.getByLabelText('愿景'), { target: { value: 'My new direction' } });
        fireEvent.click(screen.getByRole('button', { name: '保存工作区' }));
        await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('版本冲突'));
        expect(screen.getByLabelText('愿景')).toHaveValue('My new direction');
        expect(screen.getByText('有未保存更改')).toBeTruthy();
    });
    it('uses the same edited task in today and the weekly slot table', async () => {
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('添加主任务'));
        fireEvent.click(screen.getByText('添加主任务'));
        fireEvent.change(screen.getByLabelText('任务标题'), { target: { value: 'One authoritative task' } });
        fireEvent.change(screen.getByLabelText('计划时段'), { target: { value: 'morning' } });
        fireEvent.click(screen.getByText('周计划'));
        fireEvent.click(screen.getByText('One authoritative task · 未开始'));
        expect(screen.getByLabelText('任务标题')).toHaveValue('One authoritative task');
        expect(screen.getByLabelText('计划时段')).toHaveValue('morning');
    });
    it('does not let a delayed response restore the previous account content', async () => {
        let release!: (value: typeof workspace) => void;
        (getLifeWorkspace as ReturnType<typeof vi.fn>).mockReturnValueOnce(new Promise(resolve => { release = resolve; })).mockResolvedValueOnce(workspace);
        const view = render(<LifeNavigationWorkspace />);
        user = { id: 8 };
        view.rerender(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('方向与季度'));
        const privateData = blankData();
        privateData.strategy.vision = 'Old account content';
        release({ ...workspace, data: privateData });
        fireEvent.click(screen.getByText('方向与季度'));
        expect(screen.getByLabelText('愿景')).toHaveValue('');
    });
    it('keeps timer completion separate from task completion', async () => {
        (saveLifeWorkspace as ReturnType<typeof vi.fn>).mockImplementation(async (_owner, revision, data) => ({ ...workspace, revision: revision + 1, data }));
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('添加主任务'));
        fireEvent.click(screen.getByText('添加主任务'));
        fireEvent.change(screen.getByLabelText('任务标题'), { target: { value: 'Independent task' } });
        fireEvent.click(screen.getByText('时段导航'));
        fireEvent.click(screen.getByText('开始并保存'));
        await waitFor(() => screen.getByText('结束计时并保存'));
        fireEvent.click(screen.getByText('结束计时并保存'));
        await waitFor(() => expect(saveLifeWorkspace).toHaveBeenCalledTimes(2));
        const saved = (saveLifeWorkspace as ReturnType<typeof vi.fn>).mock.calls[1][2];
        expect((Object.values(saved.weeks)[0] as any).tasks[0].status).toBe('planned');
        expect(saved.focus.phase).toBe('idle');
    });
    it('shows workspace versions and restores only after explicit confirmation', async () => {
        (getLifeHistory as ReturnType<typeof vi.fn>).mockResolvedValue([{ revision: 2, data: blankData(), updated_at: '2026-10-09T00:00:00Z' }]);
        const confirmation = vi.spyOn(window, 'confirm').mockReturnValue(false);
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('备份'));
        fireEvent.click(screen.getByText('备份'));
        await waitFor(() => screen.getByText('恢复版本 2'));
        fireEvent.click(screen.getByText('恢复版本 2'));
        expect(restoreLifeWorkspace).not.toHaveBeenCalled();
        confirmation.mockRestore();
    });
    it('generates a review draft without overwriting the authored review', async () => {
        const data = blankData(); data.weeks['2026-10-05'] = { tracks: [], tasks: [], notes: { '2026-10-09': { valuable: '', beautiful: '', mistake: '', learning: 'Observed lesson' } }, review: { summary: 'Authored summary', gap: '', learning: '', next_week: '' }, archives: [] };
        (getLifeWorkspace as ReturnType<typeof vi.fn>).mockResolvedValue({ ...workspace, data });
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('周复盘'));
        fireEvent.change(screen.getByLabelText('查看日期'), { target: { value: '2026-10-09' } });
        fireEvent.click(screen.getByText('周复盘'));
        fireEvent.click(screen.getByText('生成待核对草稿'));
        fireEvent.click(screen.getByText('仅填入空白字段'));
        expect(screen.getByLabelText('本周总结')).toHaveValue('Authored summary');
        expect(screen.getByLabelText('本周学习')).toHaveValue('2026-10-09：Observed lesson');
        expect(saveLifeWorkspace).not.toHaveBeenCalled();
    });
    it('previews imported backups before requiring replacement confirmation and retains them on conflict', async () => {
        (importLifeBackup as ReturnType<typeof vi.fn>).mockRejectedValue({ response: { status: 409 } });
        const confirmation = vi.spyOn(window, 'confirm').mockReturnValue(false);
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('备份'));
        fireEvent.click(screen.getByText('方向与季度'));
        fireEvent.change(screen.getByLabelText('愿景'), { target: { value: 'My unsaved draft' } });
        fireEvent.click(screen.getByText('备份'));
        const file = new File([JSON.stringify({ schema_version: 'life_navigation.backup.v1', workspace, history: [] })], 'backup.json', { type: 'application/json' });
        Object.defineProperty(file, 'text', { value: async () => JSON.stringify({ schema_version: 'life_navigation.backup.v1', workspace, history: [] }) });
        fireEvent.change(screen.getByLabelText('选择备份预览'), { target: { files: [file] } });
        await waitFor(() => screen.getByText('导入预览'));
        expect(importLifeBackup).not.toHaveBeenCalled();
        fireEvent.click(screen.getByText('确认替换并导入'));
        expect(importLifeBackup).not.toHaveBeenCalled();
        confirmation.mockReturnValue(true);
        fireEvent.click(screen.getByText('确认替换并导入'));
        await waitFor(() => expect(screen.getByRole('alert')).toHaveTextContent('版本冲突'));
        expect(screen.getByText('导入预览')).toBeTruthy();
        fireEvent.click(screen.getByText('方向与季度'));
        expect(screen.getByLabelText('愿景')).toHaveValue('My unsaved draft');
        confirmation.mockRestore();
    });
    it('restores an existing persisted focus deadline when the screen is reopened', async () => {
        const data = blankData(); data.focus = { ...data.focus, phase: 'focus', deadline: new Date(Date.now() + 1400000).toISOString() };
        (getLifeWorkspace as ReturnType<typeof vi.fn>).mockResolvedValue({ ...workspace, data });
        render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('时段导航'));
        fireEvent.click(screen.getByText('时段导航'));
        expect(screen.getByText('暂停并保存')).toBeTruthy();
        expect(screen.queryByText('开始并保存')).toBeNull();
        expect(saveLifeWorkspace).not.toHaveBeenCalled();
    });
    it('drops the previous account local state when user changes', async () => {
        const view = render(<LifeNavigationWorkspace />);
        await waitFor(() => screen.getByText('方向与季度'));
        fireEvent.click(screen.getByText('方向与季度'));
        fireEvent.change(screen.getByLabelText('愿景'), { target: { value: 'Private account A draft' } });
        user = { id: 8 };
        view.rerender(<LifeNavigationWorkspace />);
        await waitFor(() => expect(getLifeWorkspace).toHaveBeenCalledWith(8, expect.any(AbortSignal)));
        fireEvent.click(screen.getByText('方向与季度'));
        expect(screen.getByLabelText('愿景')).toHaveValue('');
    });
});
