#!/usr/bin/env python3
"""Generate docs/_generated/mobile-nav-graph.json — mobile 页面导航知识图谱(代码派生)。

System-map facet-6 的 mobile 动线骨架:节点 = expo-router 路由(mobile/app/**/*.tsx),
边 = 代码里的跳转(router.push/replace/navigate、<Link href>、Redirect href)。
**边只准从代码派生**(改 UI 即重生成),不手画 → 不漂。配 docs/system-map/mobile-nav-map.md(叙事:动线+合理性)。

Usage:
  python mobile/scripts/dump_nav_graph.py            # 写 JSON
  python mobile/scripts/dump_nav_graph.py --check    # 只读检查生成物是否漂移
  python mobile/scripts/dump_nav_graph.py --summary  # 额外打印孤儿/死胡同摘要
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

MOBILE = Path(__file__).resolve().parent.parent
APP = MOBILE / "app"
OUT = MOBILE.parent / "docs" / "_generated" / "mobile-nav-graph.json"

# 排除:布局/特殊文件/测试
_EXCLUDE_NAMES = {"_layout.tsx", "+html.tsx", "+not-found.tsx"}
_EXCLUDE_SUFFIX = (".test.tsx", ".spec.tsx")


def _file_to_route(p: Path) -> str:
    """expo-router 文件路径 → 路由。 (tabs)/index→/, (tabs)/chat→/chat, diet→/diet, card/[id]→/card/[id]."""
    rel = p.relative_to(APP).with_suffix("")
    parts = [seg for seg in rel.parts if not (seg.startswith("(") and seg.endswith(")"))]
    if not parts:
        return "/"
    if parts[-1] == "index":
        parts = parts[:-1]
    route = "/" + "/".join(parts)
    return route if route != "" else "/"


def _list_routes() -> dict[str, Path]:
    routes: dict[str, Path] = {}
    for p in sorted(APP.rglob("*.tsx")):
        if p.name in _EXCLUDE_NAMES or p.name.endswith(_EXCLUDE_SUFFIX):
            continue
        if "__tests__" in p.parts:
            continue
        routes[_file_to_route(p)] = p
    return routes


# 跳转抽取:捕获以 / 开头的路由字面量
_EDGE_PATTERNS = [
    r"router\.(?:push|replace|navigate)\(\s*['\"`](/[^'\"`]*)['\"`]",
    r"\.(?:push|replace|navigate)\(\s*['\"`](/[^'\"`]*)['\"`]",   # useRouter() 解构后裸 push(...)
    r"href\s*=\s*['\"`](/[^'\"`]*)['\"`]",                          # <Link href="/x">
    r"href\s*=\s*\{\s*['\"`](/[^'\"`]*)['\"`]\s*\}",                # href={'/x'}
    r"pathname:\s*['\"`](/[^'\"`]*)['\"`]",                          # push({pathname:'/x'})
    r"<Redirect\s+href=['\"`](/[^'\"`]*)['\"`]",
]


def _normalize_target(t: str) -> str:
    t = t.split("?")[0].rstrip("/")            # 去 query / 尾斜杠
    t = re.sub(r"/\$\{[^}]+\}", "/[id]", t)    # 模板插值 → [id]
    # 剥 expo-router 分组段 (tabs) 等:/(tabs)/chat → /chat(与 _file_to_route 一致)
    segs = [s for s in t.split("/") if not (s.startswith("(") and s.endswith(")"))]
    t = "/".join(segs)
    if not t.startswith("/"):
        t = "/" + t
    return t or "/"


def _extract_edges(text: str) -> set[str]:
    out: set[str] = set()
    for pat in _EDGE_PATTERNS:
        for m in re.finditer(pat, text):
            out.add(_normalize_target(m.group(1)))
    return out


def _match_route(target: str, route_set: set[str]) -> str | None:
    """把跳转目标对到已知路由(处理动态段 [id] 与去前缀)。"""
    if target in route_set:
        return target
    # 动态段:/card/123 → /card/[id]
    segs = target.strip("/").split("/")
    for r in route_set:
        rsegs = r.strip("/").split("/")
        if len(rsegs) != len(segs):
            continue
        if all(rs == s or (rs.startswith("[") and rs.endswith("]")) for rs, s in zip(rsegs, segs)):
            return r
    return None


def build_graph() -> dict:
    routes = _list_routes()
    route_set = set(routes)
    nodes = sorted(route_set)
    edges: list[dict] = []
    edge_seen: set[tuple[str, str]] = set()
    external: dict[str, list[str]] = {}  # 跳到未知路由(可能漂移/拼错)

    for route, p in routes.items():
        text = p.read_text(encoding="utf-8", errors="ignore")
        for tgt in sorted(_extract_edges(text)):
            matched = _match_route(tgt, route_set)
            if matched is None:
                external.setdefault(route, []).append(tgt)
                continue
            if matched == route:
                continue
            key = (route, matched)
            if key not in edge_seen:
                edge_seen.add(key)
                edges.append({"from": route, "to": matched})

    # 图分析(合理性信号)
    out_deg: dict[str, int] = {n: 0 for n in nodes}
    in_deg: dict[str, int] = {n: 0 for n in nodes}
    for e in edges:
        out_deg[e["from"]] += 1
        in_deg[e["to"]] += 1

    TABS = ["/", "/chat", "/record", "/me"]  # 4 可见 tab(全局可达入口)
    orphans = sorted(n for n in nodes if in_deg[n] == 0 and n not in TABS)
    dead_ends = sorted(n for n in nodes if out_deg[n] == 0)

    return {
        "_note": "DO NOT EDIT — generated by mobile/scripts/dump_nav_graph.py. 改导航后重生成。",
        "counts": {
            "nodes": len(nodes),
            "edges": len(edges),
            "orphans": len(orphans),        # 无入边(除 tab)= 代码里没人跳过去 = 可能不可达
            "dead_ends": len(dead_ends),    # 无出边 = 终点页
            "external_unmatched": sum(len(v) for v in external.values()),
        },
        "tabs": TABS,
        "nodes": nodes,
        "edges": edges,
        "orphans": orphans,
        "dead_ends": dead_ends,
        "external_unmatched": dict(sorted(external.items())),
    }


def main(argv: list[str]) -> int:
    g = build_graph()
    if "--check" in argv:
        if not OUT.exists():
            print(f"❌ missing generated navigation graph: {OUT}", file=sys.stderr)
            return 1
        try:
            committed = json.loads(OUT.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            print(f"❌ cannot read generated navigation graph {OUT}: {exc}", file=sys.stderr)
            return 1
        if committed != g:
            print(
                "❌ mobile navigation graph drifted; "
                "run python mobile/scripts/dump_nav_graph.py and commit the result",
                file=sys.stderr,
            )
            return 1
        print("✅ mobile navigation graph is up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(g, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"✅ wrote {OUT.relative_to(MOBILE.parent)}")
    print(json.dumps(g["counts"], ensure_ascii=False, indent=2))
    if "--summary" in argv:
        print("\n孤儿页(无入边,可能不可达):")
        for n in g["orphans"]:
            print(f"  {n}")
        print(f"\n跳到未知路由(可能拼错/漂移){g['counts']['external_unmatched']} 条:")
        for src, tgts in g["external_unmatched"].items():
            print(f"  {src} → {tgts}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
