import React from 'react';
import { Alert, AppState } from 'react-native';
import { render, waitFor, fireEvent, act } from '@testing-library/react-native';
let mockOwner = 1;
jest.mock('../../hooks/useAuth', () => ({ useAuth: () => ({ user: { id: mockOwner } }) }));
jest.mock('expo-router', () => ({ useRouter: () => ({ push: jest.fn() }), Stack: { Screen: () => null }, useFocusEffect: (cb: () => void) => require('react').useEffect(cb, [cb]) }));
jest.mock('../../services/lifeNavigation', () => ({ fetchLifeWorkspace: jest.fn(), saveLifeWorkspace: jest.fn(), fetchLifeHistory: jest.fn().mockResolvedValue([]), restoreLifeWorkspace: jest.fn(), fetchLifeBackup: jest.fn(), importLifeBackup: jest.fn() }));
import { fetchLifeWorkspace, saveLifeWorkspace, fetchLifeHistory, importLifeBackup, restoreLifeWorkspace } from '../../services/lifeNavigation';
jest.mock('../../utils/lifeNavigationFiles', () => ({ exportLifeBackup: jest.fn(), pickLifeBackup: jest.fn() }), { virtual: true });
import Screen from '../life-navigation';
import { blankData, blankTask, blankWeek, localDate, mondayOf } from '../../utils/lifeNavigationModel';
import { invalidateAIConsent } from '../../services/aiConsentState';
import { pickLifeBackup } from '../../utils/lifeNavigationFiles';
const workspace = () => ({ schema_version: 'life_navigation.v1', revision: 0, updated_at: null, data: blankData() });
beforeEach(() => { mockOwner = 1; jest.clearAllMocks();jest.spyOn(AppState,'addEventListener').mockImplementation(()=>({remove:jest.fn()})); (fetchLifeWorkspace as jest.Mock).mockResolvedValue(workspace()); });
it('only reports a personal task saved after the server confirms', async () => {
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue({ revision: 0, data: { weeks: {} } });
    (saveLifeWorkspace as jest.Mock).mockRejectedValue({ response: { status: 409 } });
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.changeText(view.getByLabelText('个人任务标题'), '读书');
    fireEvent.press(view.getByText('加入今日安排'));
    fireEvent.press(view.getByText('保存个人安排'));
    await waitFor(() => view.getByText('另一设备已更新，草稿已保留，请重新读取后核对。'));
    expect(view.queryByText('已保存个人安排')).toBeNull();
    expect(view.getAllByDisplayValue('读书')).toHaveLength(1);
});
it('clears write busy after an in-flight save crosses background and foreground', async () => {
    let listener!: (state: string) => void;
    jest.spyOn(AppState, 'addEventListener').mockImplementation((_event, callback) => { listener = callback as (state: string) => void; return { remove: jest.fn() }; });
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue({ revision: 0, data: { weeks: {} } });
    let finish!: (value: unknown) => void;
    (saveLifeWorkspace as jest.Mock).mockImplementation(() => new Promise(resolve => { finish = resolve; }));
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.changeText(view.getByLabelText('个人任务标题'), '读书');
    fireEvent.press(view.getByText('加入今日安排'));
    fireEvent.press(view.getByText('保存个人安排'));
    act(() => { listener('background'); listener('active'); });
    await act(async () => { finish({ revision: 1, data: { weeks: {} } }); });
    await waitFor(() => expect(view.getByLabelText('加入今日安排').props.accessibilityState.disabled).toBe(false));
    jest.restoreAllMocks();
});
it('offers all eight native views and never writes merely navigating', async () => {
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue({ revision: 0, data: { weeks: {} } });
    (saveLifeWorkspace as jest.Mock).mockClear();
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    for (const label of ['今日', '周计划', '时段导航', '周复盘', '成果', '方向与季度', '机会', '备份'])
        expect(view.getByLabelText(label)).toBeTruthy();
    fireEvent.press(view.getByLabelText('方向与季度'));
    expect(view.getByLabelText('愿景')).toBeTruthy();
    fireEvent.changeText(view.getByLabelText('愿景'), '自己的方向');
    expect(saveLifeWorkspace).not.toHaveBeenCalled();
});
it('creates a task in the selected weekly time slot',async()=>{
 const view=render(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));
 fireEvent.press(view.getByLabelText('周计划'));
 const day=localDate();fireEvent.press(view.getByLabelText('添加安排 '+day+' morning'));
 fireEvent.changeText(view.getByLabelText('个人任务标题'),'晨间阅读');fireEvent.press(view.getByText('加入今日安排'));
 fireEvent.press(view.getByText('保存个人安排'));
 await waitFor(()=>expect(saveLifeWorkspace).toHaveBeenCalled());
 expect((saveLifeWorkspace as jest.Mock).mock.calls[0][2].weeks[mondayOf(day)].tasks[0].slot).toBe('morning');
});
it('uses one task across today and the seven day table and enforces one main', async () => {
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.changeText(view.getByLabelText('个人任务标题'), '阅读');
    fireEvent.press(view.getByText('加入今日安排'));
    fireEvent.changeText(view.getByLabelText('个人任务标题'), '第二主任务');
    fireEvent.press(view.getByText('加入今日安排'));
    expect(view.getByText('每日最多一项主任务、两项辅助任务，每周最多100项任务。')).toBeTruthy();
    fireEvent.press(view.getByLabelText('周计划'));
    expect(view.getByText('阅读')).toBeTruthy();
    fireEvent.press(view.getByText('阅读'));
    expect(view.getByDisplayValue('阅读')).toBeTruthy();
    expect(saveLifeWorkspace).not.toHaveBeenCalled();
});
it('preserves manually written review while generating a draft from actual notes', async () => {
    const w = workspace(), day = localDate(), key = mondayOf(day);
    w.data.weeks[key] = blankWeek();
    w.data.weeks[key].review.summary = '人工总结';
    w.data.weeks[key].notes[day] = { valuable: '', beautiful: '', mistake: '', learning: '实际所学' };
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue(w);
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.press(view.getByLabelText('周复盘'));
    fireEvent.press(view.getByText('生成实际记录草稿'));
    fireEvent.press(view.getByText('仅填入空白复盘字段'));
    expect(view.getByLabelText('复盘总结').props.value).toBe('人工总结');
    expect(view.getByLabelText('复盘收获').props.value).toContain('实际所学');
    expect(saveLifeWorkspace).not.toHaveBeenCalled();
});
it('requires native confirmation before importing and retains the draft after conflict', async () => {
    (pickLifeBackup as jest.Mock).mockResolvedValue({ schema_version: 'life_navigation.backup.v1', workspace: workspace(), history: [] });
    (importLifeBackup as jest.Mock).mockRejectedValue({ response: { status: 409 } });
    const dialog = jest.spyOn(Alert, 'alert');
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.press(view.getByLabelText('方向与季度'));
    fireEvent.changeText(view.getByLabelText('愿景'), '本地草稿');
    fireEvent.press(view.getByLabelText('备份'));
    fireEvent.press(view.getByText('选择备份并预览'));
    await waitFor(() => view.getByText('确认替换工作区'));
    fireEvent.press(view.getByText('确认替换工作区'));
    expect(importLifeBackup).not.toHaveBeenCalled();
    await act(async () => { dialog.mock.calls[0][2]![1].onPress!(); });
    await waitFor(() => view.getByText('另一设备已更新，草稿已保留，请重新读取后核对。'));
    expect(view.getByText('确认替换工作区')).toBeTruthy();
    fireEvent.press(view.getByLabelText('方向与季度'));
    expect(view.getByLabelText('愿景').props.value).toBe('本地草稿');
    dialog.mockRestore();
});
it('ends persisted focus without completing its linked task', async () => {
    const w = workspace(), day = localDate(), key = mondayOf(day), task = blankTask(day, 'main');
    task.title = '计时任务';
    w.data.weeks[key] = blankWeek();
    w.data.weeks[key].tasks = [task];
    w.data.focus = { ...w.data.focus, phase: 'focus', deadline: new Date(Date.now() + 60000).toISOString(), task_id: task.id };
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue(w);
    (saveLifeWorkspace as jest.Mock).mockImplementation((_owner, revision, data) => Promise.resolve({ ...w, revision: revision + 1, data }));
    const view = render(<Screen />);
    await waitFor(() => view.getByDisplayValue('计时任务'));
    fireEvent.press(view.getByLabelText('时段导航'));
    fireEvent.press(view.getByText('结束计时并保存'));
    await waitFor(() => expect(saveLifeWorkspace).toHaveBeenCalled());
    expect((saveLifeWorkspace as jest.Mock).mock.calls[0][2].weeks[key].tasks[0].status).toBe('planned');
    expect((saveLifeWorkspace as jest.Mock).mock.calls[0][2].focus.phase).toBe('idle');
});
it('discards a previous account delayed read and resets unsaved input', async () => {
    let finish!: (w: unknown) => void;
    (fetchLifeWorkspace as jest.Mock).mockImplementationOnce(() => new Promise(r => finish = r));
    const view = render(<Screen />);
    mockOwner = 2;
    view.rerender(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    const old = workspace();
    old.data.strategy.vision = '旧账号秘密';
    await act(async () => finish(old));
    fireEvent.press(view.getByLabelText('方向与季度'));
    expect(view.getByLabelText('愿景').props.value).toBe('');
    expect(fetchLifeWorkspace).toHaveBeenLastCalledWith(2);
});
it('hides private content in background and restores the same unsaved draft with its revision', async () => {
    let listener!: (state: string) => void;
    const spy = jest.spyOn(AppState, 'addEventListener').mockImplementation((_event, callback) => { listener = callback as (state: string) => void; return { remove: jest.fn() }; });
    const w = workspace();
    w.revision = 7;
    (fetchLifeWorkspace as jest.Mock).mockResolvedValue(w);
    (saveLifeWorkspace as jest.Mock).mockRejectedValue({ response: { status: 409 } });
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.press(view.getByLabelText('方向与季度'));
    fireEvent.changeText(view.getByLabelText('愿景'), '未保存私密草稿');
    act(() => listener('inactive'));
    act(() => listener('background'));
    expect(view.queryByDisplayValue('未保存私密草稿')).toBeNull();
    act(() => listener('active'));
    expect(view.getByLabelText('愿景').props.value).toBe('未保存私密草稿');
    fireEvent.press(view.getByText('保存个人安排'));
    await waitFor(() => expect(saveLifeWorkspace).toHaveBeenCalled());
    expect((saveLifeWorkspace as jest.Mock).mock.calls[0][1]).toBe(7);
    spy.mockRestore();
});
it('cannot restore suspended content after consent or account invalidation', async () => {
    let listener!: (state: string) => void;
    const spy = jest.spyOn(AppState, 'addEventListener').mockImplementation((_event, callback) => { listener = callback as (state: string) => void; return { remove: jest.fn() }; });
    const view = render(<Screen />);
    await waitFor(() => view.getByText('还没有个人安排。'));
    fireEvent.press(view.getByLabelText('方向与季度'));
    fireEvent.changeText(view.getByLabelText('愿景'), '失效账号草稿');
    act(() => listener('background'));
    act(() => invalidateAIConsent());
    act(() => listener('active'));
    await waitFor(() => view.getByLabelText('愿景'));
    expect(view.getByLabelText('愿景').props.value).toBe('');
    spy.mockRestore();
});
it('requires confirmation before restoring a historical workspace', async () => {
 const old=workspace();old.revision=3;
 (fetchLifeHistory as jest.Mock).mockResolvedValue([{revision:3,updated_at:'2026-10-10T00:00:00Z',data:old.data}]);
 (restoreLifeWorkspace as jest.Mock).mockResolvedValue({...old,revision:4});const dialog=jest.spyOn(Alert,'alert');
 const view=render(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));fireEvent.press(view.getByLabelText('备份'));fireEvent.press(view.getByText('读取最近20个版本'));await waitFor(()=>view.getByText('恢复版本 3'));
 fireEvent.press(view.getByText('恢复版本 3'));expect(restoreLifeWorkspace).not.toHaveBeenCalled();await act(async()=>dialog.mock.calls[0][2]![1].onPress!());expect(restoreLifeWorkspace).toHaveBeenCalledWith(1,3,0);dialog.mockRestore();
});
it('ignores a backup picker returning after switching account',async()=>{
 let finish!:(value:unknown)=>void;(pickLifeBackup as jest.Mock).mockImplementation(()=>new Promise(resolve=>finish=resolve));
 const view=render(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));fireEvent.press(view.getByLabelText('备份'));fireEvent.press(view.getByText('选择备份并预览'));mockOwner=2;view.rerender(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));
 await act(async()=>finish({schema_version:'life_navigation.backup.v1',workspace:workspace(),history:[]}));fireEvent.press(view.getByLabelText('备份'));expect(view.queryByText('确认替换工作区')).toBeNull();
});

it('allows its own picker inactive active handoff and previews only in the same session',async()=>{
 let listener!:(s:string)=>void;jest.spyOn(AppState,'addEventListener').mockImplementation((_e,cb)=>{listener=cb as (s:string)=>void;return {remove:jest.fn()}});let finish!:(v:unknown)=>void;(pickLifeBackup as jest.Mock).mockImplementation(()=>new Promise(r=>finish=r));
 const view=render(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));fireEvent.press(view.getByLabelText('备份'));fireEvent.press(view.getByText('选择备份并预览'));act(()=>listener('inactive'));act(()=>listener('active'));await act(async()=>finish({schema_version:'life_navigation.backup.v1',workspace:workspace(),history:[]}));expect(view.getByText('确认替换工作区')).toBeTruthy();
});
it('cancels picker results after a real background transition',async()=>{
 let listener!:(s:string)=>void;jest.spyOn(AppState,'addEventListener').mockImplementation((_e,cb)=>{listener=cb as (s:string)=>void;return {remove:jest.fn()}});let finish!:(v:unknown)=>void;(pickLifeBackup as jest.Mock).mockImplementation(()=>new Promise(r=>finish=r));
 const view=render(<Screen/>);await waitFor(()=>view.getByText('还没有个人安排。'));fireEvent.press(view.getByLabelText('备份'));fireEvent.press(view.getByText('选择备份并预览'));act(()=>listener('inactive'));act(()=>listener('background'));act(()=>listener('active'));await act(async()=>finish({schema_version:'life_navigation.backup.v1',workspace:workspace(),history:[]}));expect(view.queryByText('确认替换工作区')).toBeNull();
});
