#!/usr/bin/env python3
"""Generate docs/_generated/system-map.json — 代码派生的系统事实(计数 + roster)。

System-map 防漂移核心(见 .claude/skills/system-map/SKILL.md + docs/system-map/INDEX.md):
一个事实只允许两种状态 —— ① 从代码生成进无人手改的文件,或 ② 带 last-reviewed 日期的纯叙事(显式不含 live 数字)。
本脚本产出 ①。复用 scripts/check_doc_drift.py 的扫描器(单一真源,别复制计数逻辑)。

输出是**确定性的**(全部 sorted,无时间戳)→ check_doc_drift.py 重算后可直接相等比对,
committed 与代码不符即 CI 红(跑本脚本重新生成即修)。

Usage:
  python scripts/dump_system_map.py          # 写 docs/_generated/system-map.json
  python scripts/dump_system_map.py --check   # 只比对,不写(committed == fresh?)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "scripts"
OUT = ROOT / "docs" / "_generated" / "system-map.json"

sys.path.insert(0, str(SCRIPTS))
import check_doc_drift as cdd  # noqa: E402  复用扫描器,不复制计数逻辑


def _specialist_roster() -> list[str]:
    return cdd.specialist_roster()


def _twin_partition_roster() -> list[str]:
    return cdd.twin_partition_roster()


def build_map() -> dict:
    """单一真源的代码派生系统事实。确定性(sorted,无时间戳)。"""
    rules = cdd.count_register_decorators(
        cdd.BACKEND / "app" / "agents" / "safety_guardian" / "rules"
    )
    return {
        "_note": "DO NOT EDIT — generated by scripts/dump_system_map.py from code. "
                 "改代码后跑该脚本重新生成;CI(check_doc_drift.py)校验本文件与代码一致。",
        "counts": {
            "safety_rules_total": sum(rules.values()),
            "specialists": cdd.count_specialists(),
            "twin_partitions": cdd.count_twin_partitions(),
            "api_routers": cdd.count_api_include_routers(),
            "celery_tasks": cdd.count_celery_tasks(),
            "model_files": cdd.count_model_files(),
            "service_files": cdd.count_service_files(),
            "mobile_routes": cdd.count_mobile_routes(),
            "web_pages": cdd.count_web_pages(),
        },
        "safety_rules_by_category": dict(sorted(rules.items())),
        "specialists_roster": _specialist_roster(),
        "twin_partitions_roster": _twin_partition_roster(),
    }


def _serialize(m: dict) -> str:
    return json.dumps(m, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def main(argv: list[str]) -> int:
    fresh = build_map()
    if "--check" in argv:
        if not OUT.exists():
            print(f"❌ {OUT} 缺失,跑 scripts/dump_system_map.py", file=sys.stderr)
            return 1
        committed = json.loads(OUT.read_text(encoding="utf-8"))
        if committed != fresh:
            print(f"❌ {OUT} 与代码不符,跑 scripts/dump_system_map.py 重新生成", file=sys.stderr)
            return 1
        print(f"✅ {OUT.relative_to(ROOT)} 与代码一致")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(_serialize(fresh), encoding="utf-8")
    print(f"✅ wrote {OUT.relative_to(ROOT)}")
    print(_serialize(fresh["counts"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
