"""Fixed pre-useradd incident recovery. No generic retry, checkout, or key rotation."""
import ast
import fcntl
import hashlib
import json
import os
from pathlib import Path
import pwd
import grp
import re
import stat
import subprocess
import sys
import tarfile
import time

FAILED_SHA = '051ee281f8247d162bcdef7b3f93fdf51930c94c'
STATE = Path('/var/lib/reva-release')
LEASE = Path('/var/lock/health-app-release')
BACKUPS = Path('/var/backups/health-app/host-security')
VOLATILE = Path('/run/lock')
ALLOWED_CHANGES = {
    'scripts/harden_public_host.py', 'scripts/trusted_public_host.py',
    'scripts/public_host_recovery.py', 'scripts/bootstrap_trusted_release.py',
    'scripts/test_public_host_boundaries.py', 'docs/governance/deploy.md',
    'docs/security/2026-09-30-host-preflight-recovery.md',
    'scripts/runtime_permission_repair.py',
    'deploy.sh', 'backend/scripts/verify_locked_requirements.py',
    'backend/scripts/rollback_release.sh', 'scripts/test_deploy_script.py',
    'scripts/test_verify_locked_requirements.py', 'scripts/test_release_rollback.py',
}

# Independently reviewed concurrent merge: only these exact non-host blobs.
REVIEWED_AUXILIARY = {
    '.github/workflows/trusted-ota.yml': b'100644 blob a19c0b2cb7689a6b9ada9afb5430cd5c10cd00a2',
    'scripts/test_trusted_ota_workflow.py': b'100644 blob 43311f7a0da49be911f3deda1678b4883904259e',
    'docs/dossiers/2026-09-30-share-composer-back-navigation.md': b'100644 blob 4eb1639b9990b66edd946b96d5c39161d572be9d',
}
BACKUP_NAMES = {'intent.json', 'config-before.tar.gz', 'config-manifest.json',
                'iptables-before.txt', 'ip6tables-before.txt'}
AUDIT_NAMES = {'started.json', 'failed.json', 'frontend.json'}
SERVICES = ('health-backend', 'celery-worker', 'celery-beat',
            'lighthouse-validator', 'lighthouse-beacon', 'eth1')


class RecoveryError(Exception):
    """Static diagnostics only."""


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def firewall_policy(raw):
    result = []
    for line in raw.splitlines():
        if line.startswith('# Generated by iptables-save ') or line.startswith('# Generated by ip6tables-save ') or line.startswith('# Completed on '):
            continue
        if line.startswith('#') or not line:
            raise RecoveryError('unknown firewall serialization')
        result.append(re.sub(r'^(:\S+ \S+) \[\d+:\d+\]$', r'\1 [COUNTERS]', line))
    if not result or result[-1] != 'COMMIT':
        raise RecoveryError('incomplete firewall snapshot')
    return result


def write_set():
    units = Path('/etc/systemd/system')
    return [units / 'health-frontend.service', units / 'health-network-guard.service',
            units / 'health-frontend-security-preflight.service',
            *(units / f'{name}.service.d/security-network.conf' for name in SERVICES[:3]),
            Path('/etc/ufw/user.rules'), Path('/etc/ufw/user6.rules'), Path('/root/.pm2/dump.pm2')]


def source_scope(source, old, guard):
    def tree(path):
        raw = subprocess.check_output(['/usr/bin/git', '-C', str(path), 'ls-tree', '-rz', '--full-tree', 'HEAD'])
        return dict(row.split(b'\t', 1)[::-1] for row in raw.split(b'\0') if row)
    before, after = tree(old), tree(source)
    changed = {p.decode() for p in before.keys() | after.keys() if before.get(p) != after.get(p)}
    if not changed or any(path not in ALLOWED_CHANGES and (path not in REVIEWED_AUXILIARY or after.get(path.encode()) != REVIEWED_AUXILIARY[path])
                          for path in changed):
        raise RecoveryError('recovery source changes exceed fixed scope')
    # The persistent network unit executes the production helper. Its entire
    # rule implementation must remain identical to the independently reviewed executor.
    def functions(path):
        return {node.name: ast.dump(node, include_attributes=False) for node in ast.parse(path.read_text()).body if isinstance(node, ast.FunctionDef)}
    old_functions = functions(old / 'scripts/harden_public_host.py')
    new_functions = functions(source / 'scripts/harden_public_host.py')
    def ports(path):
        nodes = [node for node in ast.parse(path.read_text()).body if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == 'APPLICATION_PORTS' for target in node.targets)]
        if len(nodes) != 1:
            raise RecoveryError('persistent network policy constant differs')
        return ast.dump(nodes[0], include_attributes=False)
    if ports(old / 'scripts/harden_public_host.py') != ports(source / 'scripts/harden_public_host.py'):
        raise RecoveryError('persistent network policy constant differs')
    for name in ('firewall_rules', 'canonical_rule', 'network_guard'):
        if old_functions[name] != new_functions[name]:
            raise RecoveryError('persistent network policy changed')
    return sorted(changed)


def verify_backup(backup, guard, *, live=True):
    manifest = json.loads((backup / 'config-manifest.json').read_bytes())
    expected_paths = list(map(str, write_set()))
    if not isinstance(manifest, list) or [x.get('path') for x in manifest] != expected_paths:
        raise RecoveryError('backup write set differs')
    with tarfile.open(backup / 'config-before.tar.gz', 'r:gz') as archive:
        members = archive.getmembers()
        expected = [x for x in manifest if x.get('exists') is True]
        if len(members) != len(expected) or {m.name for m in members} != {x['path'].lstrip('/') for x in expected}:
            raise RecoveryError('backup archive inventory differs')
        for entry in manifest:
            path = Path(entry['path'])
            if entry == {'path': str(path), 'exists': False}:
                if live and os.path.lexists(path):
                    raise RecoveryError('previously absent configuration appeared')
                continue
            if set(entry) != {'path', 'exists', 'mode', 'sha256'} or entry['exists'] is not True:
                raise RecoveryError('backup manifest schema differs')
            if live:
                guard.trusted(path)
            info = path.lstat() if live else None
            member = archive.getmember(str(path).lstrip('/'))
            if (not member.isfile() or member.uid != 0 or member.gid != 0 or member.mode != entry['mode']
                    or (live and (member.uid != info.st_uid or member.gid != info.st_gid or stat.S_IMODE(info.st_mode) != entry['mode']))
                    or member.size > 16000000):
                raise RecoveryError('backup metadata differs')
            with archive.extractfile(member) as stream:
                archived = stream.read(16000001)
            if hashlib.sha256(archived).hexdigest() != entry['sha256'] or (live and hashlib.sha256(path.read_bytes()).hexdigest() != entry['sha256']):
                raise RecoveryError('live configuration or archive changed')
    return manifest


def process_identity(pid):
    root = Path('/proc') / str(pid)
    raw = (root / 'stat').read_bytes()
    fields = raw.rsplit(b')', 1)[-1].split()
    status = dict(row.split(':', 1) for row in (root / 'status').read_text().splitlines() if ':' in row)
    result = {'pid': int(pid), 'starttime': fields[19].decode(),
              'uid': status['Uid'].split(), 'cgroup': (root / 'cgroup').read_text(),
              'argv_sha256': hashlib.sha256((root / 'cmdline').read_bytes()).hexdigest()}
    if (root / 'stat').read_bytes().rsplit(b')', 1)[-1].split()[19] != fields[19]:
        raise RecoveryError('process identity changed')
    return result


def services(guard):
    result = {}
    for name in SERVICES:
        props = dict(row.split('=', 1) for row in guard.run('/usr/bin/systemctl', 'show', name,
            '-p', 'ActiveState,MainPID,NRestarts,NeedDaemonReload').splitlines())
        if props['ActiveState'] != 'active' or props['NeedDaemonReload'] != 'no' or int(props['MainPID']) <= 1:
            raise RecoveryError('service is not stable')
        result[name] = {'properties': props, 'process': process_identity(props['MainPID'])}
    return result


def private_inventory(b, path, names):
    return b._inventory(path, names)


class Adapter:
    def __init__(self, source, old, publisher, host, helper, b, server, guard, token, check):
        self.source, self.old, self.publisher = source, old, publisher
        self.host, self.helper, self.b, self.server, self.guard = host, helper, b, server, guard
        self.token, self.check = token, check
        self.audit = STATE / FAILED_SHA / 'host-hardening'
        self.backup = BACKUPS / FAILED_SHA
        self.record = STATE / 'host-hardening-recoveries' / FAILED_SHA

    def lease(self):
        b = self.b
        self.helper._lease_identity(str(LEASE), self.token, b, self.server)
        proof_module = self.host.module(self.source / 'scripts/contained_recovery_proof.py', 'host_lease_proof')
        proof = proof_module.RecoveryProof.__new__(proof_module.RecoveryProof)
        proof.bootstrap, proof.lease, proof.stage = b, LEASE, None
        result = {'.': {**proof._directory(LEASE), 'sha256': None}}
        if {p.name for p in LEASE.iterdir()} != {'token', 'label', 'stage', 'started_at'}:
            raise RecoveryError('original host lease inventory differs')
        values = {}
        for name in ('token', 'label', 'stage', 'started_at'):
            values[name], result[name] = proof._file(LEASE / name, 0o600)
        validate_lease_contents(values, self.audit)
        return result

    def preserved(self):
        return {'audit': private_inventory(self.b, self.audit, AUDIT_NAMES),
                'backup': private_inventory(self.b, self.backup, BACKUP_NAMES)}

    def inspect(self):
        self.check()
        b, g = self.b, self.guard
        b._recovery_process_proof()
        self.helper._revision_proof(FAILED_SHA, self.old, b)
        if b._read_json(STATE / FAILED_SHA / 'completed.json') != {'sha': FAILED_SHA, 'state': 'SUCCEEDED'}:
            raise RecoveryError('production backend success differs')
        preserved = self.preserved()
        for name, state in (('started.json', 'STARTED'), ('failed.json', 'NEEDS_OPERATOR')):
            if b._read_json(self.audit / name) != {'sha': FAILED_SHA, 'state': state}:
                raise RecoveryError('original host failure chain differs')
        frontend = self.host.verify_frontend_artifacts(FAILED_SHA, self.old, b, self.server)
        if b._read_json(self.audit / 'frontend.json') != frontend:
            raise RecoveryError('original frontend identity differs')
        lease = self.lease()
        for lookup in (pwd.getpwnam, grp.getgrnam):
            try:
                lookup('health-web')
            except KeyError:
                continue
            raise RecoveryError('service account preparation already began')
        verify_backup(self.backup, g)
        for path in write_set():
            if os.path.lexists(path.with_name(path.name + '.reva-security-new')):
                raise RecoveryError('pending configuration write exists')
        for name in ('health-network-guard', 'health-frontend-security-preflight'):
            if any(Path('/etc/systemd/system').glob(f'*.wants/{name}.service')) or any(Path('/run/systemd/system').glob(f'*.wants/{name}.service')):
                raise RecoveryError('new service enablement exists')
            if g.run('/usr/bin/systemctl', 'show', name, '-p', 'LoadState', '--value').strip() != 'not-found':
                raise RecoveryError('new service configuration already loaded')
        if g.run('/usr/bin/systemctl', 'show', 'health-frontend', '-p', 'MainPID', '--value').strip() != '0':
            raise RecoveryError('systemd frontend is already running')
        intent = b._read_json(self.backup / 'intent.json')
        if set(intent) != {'sha', 'legacy_pid', 'key_modes'} or intent['sha'] != FAILED_SHA or type(intent['legacy_pid']) is not int:
            raise RecoveryError('backup intent differs')
        if g.pm2_frontend() != intent['legacy_pid']:
            raise RecoveryError('legacy frontend process changed')
        legacy = process_identity(intent['legacy_pid'])
        if legacy['uid'] != ['0'] * 4:
            raise RecoveryError('legacy frontend owner differs')
        g.trusted(g.STAKING, directory=True)
        keys = [p for p in g.STAKING.rglob('*') if 'keystore' in p.name and p.is_file()]
        actual_modes = []
        for path in keys:
            g.trusted(path)
            actual_modes.append({'path': str(path), 'mode': stat.S_IMODE(path.lstat().st_mode)})
        if not keys or sorted(actual_modes, key=lambda x:x['path']) != sorted(intent['key_modes'], key=lambda x:x['path']):
            raise RecoveryError('keystore inventory or modes changed')
        cache = g.ROOT / 'frontend/.next/cache'
        cache_snapshot = {}
        for index, path in enumerate([cache, *cache.rglob('*')]):
            if index > 100000:
                raise RecoveryError('cache inventory bound exceeded')
            info = path.lstat()
            if info.st_uid != 0 or info.st_gid != 0 or not (stat.S_ISREG(info.st_mode) or stat.S_ISDIR(info.st_mode)):
                raise RecoveryError('cache ownership already changed')
            cache_snapshot[str(path)] = [info.st_dev, info.st_ino, info.st_mode, info.st_uid, info.st_gid]
        firewall = {}
        for binary in ('iptables', 'ip6tables'):
            before = firewall_policy((self.backup / (binary+'-before.txt')).read_text())
            current = firewall_policy(g.run('/usr/sbin/'+binary+'-save'))
            if before != current:
                raise RecoveryError('firewall policy changed')
            firewall[binary] = before
        g.preflight_commands()
        g.ready(30001)
        live_services = services(g)
        boot = int(re.findall(r'^btime ([0-9]+)$', Path('/proc/stat').read_text(), re.M)[0])
        started = int((LEASE / 'started_at').read_text())
        permission_binding = None
        age_services = live_services
        if os.path.lexists(STATE/'runtime-permission-repairs'/FAILED_SHA):
            repair = self.host.module(self.source/'scripts/runtime_permission_repair.py','permission_history')
            repair_intent, repair_done = repair.inspect_history(self, sys.modules[__name__])
            if live_services != repair_done['after_services']:
                raise RecoveryError('services differ from completed permission repair')
            age_services = repair_intent['before']['services']
            permission_binding = {'intent_sha256':digest(repair_intent),'completion_sha256':digest(repair_done)}
        if any(boot + int(x['starttime']) / os.sysconf('SC_CLK_TCK') >= started for x in [legacy, *(v['process'] for v in age_services.values())]):
            raise RecoveryError('process does not predate host attempt')
        self.host.verify_runtime(g, check_network=False)
        self.check()
        if self.lease() != lease or self.preserved() != preserved:
            raise RecoveryError('original evidence changed during inspection')
        evidence = {'production_sha': FAILED_SHA, 'publisher_sha': self.publisher, 'preserved': preserved,
                'lease': lease, 'frontend': frontend, 'legacy': legacy, 'services': live_services,
                'cache': cache_snapshot, 'firewall': firewall, 'key_modes': intent['key_modes'], 'permission_repair':permission_binding}
        validate_intent(evidence, intent, frontend,
                        {name:(LEASE/name).read_bytes() for name in ('token','label','stage','started_at')},g)
        return evidence


def recover(adapter, evidence_sha256=None):
    a = adapter
    if os.path.lexists(a.record):
        raise RecoveryError('host recovery already attempted; replay forbidden')
    evidence = a.inspect()
    expected = digest(evidence)
    if evidence_sha256 is None:
        return {'state': 'HOST_RECOVERY_PREFLIGHT', 'production_sha': FAILED_SHA,
                'publisher_sha': a.publisher, 'evidence_sha256': expected}
    if evidence_sha256 != expected:
        raise RecoveryError('host recovery evidence changed')
    a.record.parent.mkdir(mode=0o700, exist_ok=True)
    a.server.secure_path(a.record.parent, directory=True)
    a.record.mkdir(mode=0o700)
    a.server._sync_directory(a.record.parent)
    a.server._write_private(a.record / 'intent.json', json.dumps(evidence, sort_keys=True).encode())
    if a.inspect() != evidence:
        raise RecoveryError('host recovery evidence drift after intent')
    apply_dir = a.record / 'apply'
    apply_dir.mkdir(mode=0o700)
    a.server._sync_directory(a.record)
    a.guard._apply_prepared(FAILED_SHA, apply_dir, evidence['legacy']['pid'], [Path(x['path']) for x in evidence['key_modes']])
    a.host.verify_runtime(a.guard)
    a.helper._revision_proof(FAILED_SHA, a.old, a.b)
    if services(a.guard) != evidence['services'] or a.preserved() != evidence['preserved'] or a.lease() != evidence['lease']:
        raise RecoveryError('protected services or original evidence changed')
    frontend = dict(row.split('=',1) for row in a.guard.run('/usr/bin/systemctl','show','health-frontend','-p','User,MainPID,ActiveState').splitlines())
    if frontend['User'] != 'health-web' or frontend['ActiveState'] != 'active':
        raise RecoveryError('frontend privilege boundary unproven')
    uid = str(pwd.getpwnam('health-web').pw_uid)
    if process_identity(frontend['MainPID'])['uid'] != [uid]*4:
        raise RecoveryError('frontend actual identity differs')
    archive = a.record / 'lease'
    archive.mkdir(mode=0o700)
    for name in ('token','label','stage','started_at'):
        a.server._write_private(archive / name, (LEASE / name).read_bytes())
    a.server._sync_directory(a.record)
    a.check()
    if a.lease() != evidence['lease']:
        raise RecoveryError('lease changed before retirement')
    destination = VOLATILE / ('health-app-release.host-retired-'+FAILED_SHA)
    if os.path.lexists(destination) or LEASE.lstat().st_dev != destination.parent.lstat().st_dev:
        raise RecoveryError('lease cannot be atomically archived')
    subprocess.run(['/usr/bin/mv','--no-clobber','-T','--',str(LEASE),str(destination)], check=True, timeout=15,
                   stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    a.server._sync_business_lease_parent()
    if os.path.lexists(LEASE) or destination.lstat().st_ino != evidence['lease']['.']['ino']:
        raise RecoveryError('original lease inode retirement unproven')
    result = {'state':'RECOVERED_LOCAL_VERIFIED','production_sha':FAILED_SHA,'publisher_sha':a.publisher,
              'intent_sha256':expected,'external_readback_required':True}
    a.server._write_private(a.record/'completed.json',json.dumps(result,sort_keys=True).encode())
    return result


def execute(source, host, helper, b, server, gate, guard, publisher, production, token, evidence_sha256=None, *, repair_permissions=False):
    if production != FAILED_SHA or publisher == production:
        raise RecoveryError('fixed host incident and distinct publisher required')
    gate.verify_release(publisher,publisher)
    old = b.canonical_source(FAILED_SHA)
    source_scope(source,old,guard)
    lock=STATE/'launcher.lock'
    b.secure(lock,private=True)
    with lock.open('r+b') as stream:
        fcntl.flock(stream.fileno(),fcntl.LOCK_EX|fcntl.LOCK_NB)
        build=b._acquire_existing_build_lock(FAILED_SHA)
        try:
            def check():
                b._assert_original_lock(lock,stream.fileno())
                if build is not None:b._assert_original_lock(STATE/FAILED_SHA/'build.lock',build)
            server.assert_ota_history()
            adapter=Adapter(source,old,publisher,host,helper,b,server,guard,token,check)
            if repair_permissions:
                repair=host.module(source/'scripts/runtime_permission_repair.py','runtime_permission_repair')
                return repair.execute(adapter,sys.modules[__name__],evidence_sha256)
            return recover(adapter,evidence_sha256)
        finally:
            if build is not None:os.close(build)


def validate_lease_contents(values, audit):
    if (values['label'] != b'host-hardening\n' or values['stage'] != (str(audit)+'\n').encode()
            or re.fullmatch(rb'[0-9]+\n', values['started_at']) is None
            or re.fullmatch(rb'[a-f0-9]{64}\n', values['token']) is None):
        raise RecoveryError('original host lease binding differs')


def validate_intent(intent, backup_intent, frontend, lease_values, guard):
    def require(condition):
        if not condition:
            raise RecoveryError('host recovery intent inner evidence differs')
    def integer(value, minimum=0):
        return type(value) is int and value >= minimum
    def sha(value, size=64):
        return isinstance(value, str) and re.fullmatch('[a-f0-9]{'+str(size)+'}', value) is not None
    binding=intent.get('permission_repair')
    require(binding is None or isinstance(binding,dict) and set(binding)=={'intent_sha256','completion_sha256'} and all(sha(x) for x in binding.values()))
    def process(value):
        require(isinstance(value, dict) and set(value) == {'pid','starttime','uid','cgroup','argv_sha256'})
        require(integer(value['pid'],2) and isinstance(value['starttime'],str) and value['starttime'].isdigit()
                and value['uid'] == ['0']*4 and isinstance(value['cgroup'],str) and bool(value['cgroup']) and sha(value['argv_sha256']))
    require(isinstance(frontend,dict) and set(frontend) == {'operation_id','frontend_tree','artifact_digest'})
    require(sha(frontend['operation_id'],32) and sha(frontend['frontend_tree'],40) and sha(frontend['artifact_digest']))
    require(intent['frontend'] == frontend)
    require(set(backup_intent) == {'sha','legacy_pid','key_modes'} and backup_intent['sha'] == FAILED_SHA)
    process(intent['legacy'])
    require(intent['legacy']['pid'] == backup_intent['legacy_pid'])
    require(isinstance(intent['services'],dict) and set(intent['services']) == set(SERVICES))
    for name,value in intent['services'].items():
        require(isinstance(value,dict) and set(value) == {'properties','process'})
        props=value['properties']
        require(isinstance(props,dict) and set(props) == {'ActiveState','MainPID','NRestarts','NeedDaemonReload'})
        require(props['ActiveState']=='active' and props['NeedDaemonReload']=='no'
                and isinstance(props['NRestarts'],str) and props['NRestarts'].isdigit())
        # Backend services run as health-app, staking services as root.
        proc=value['process'];uids=proc.get('uid') if isinstance(proc,dict) else None
        require(isinstance(uids,list) and len(uids)==4 and len(set(uids))==1 and all(isinstance(x,str) and x.isdigit() for x in uids))
        process({**proc,'uid':['0']*4})
        require(props['MainPID']==str(proc['pid']))
        require(int(uids[0])>0 if name in SERVICES[:3] else uids==['0']*4)
    keys=intent['key_modes']
    require(isinstance(keys,list) and bool(keys) and keys==backup_intent['key_modes'])
    require(all(isinstance(x,dict) and set(x)=={'path','mode'} and isinstance(x['path'],str)
                and Path(x['path']).is_relative_to(guard.STAKING) and '..' not in Path(x['path']).parts
                and 'keystore' in Path(x['path']).name and integer(x['mode']) and x['mode']<=0o777 for x in keys))
    require(len({x['path'] for x in keys})==len(keys))
    cache=intent['cache'];base=guard.ROOT/'frontend/.next/cache'
    require(isinstance(cache,dict) and str(base) in cache and len(cache)<=100001)
    for path,info in cache.items():
        require(Path(path).is_relative_to(base) and '..' not in Path(path).parts and isinstance(info,list) and len(info)==5
                and all(integer(x) for x in info) and info[1]>0 and info[3:]==[0,0]
                and (stat.S_ISDIR(info[2]) or stat.S_ISREG(info[2])))
    require(isinstance(intent['firewall'],dict) and set(intent['firewall'])=={'iptables','ip6tables'})
    for binary,policy in intent['firewall'].items():
        require(policy==firewall_policy((BACKUPS/FAILED_SHA/(binary+'-before.txt')).read_text()))
    lease=intent['lease']
    require(isinstance(lease,dict) and set(lease)=={'.','token','label','stage','started_at'})
    validate_lease_contents(lease_values,STATE/FAILED_SHA/'host-hardening')
    for name,info in lease.items():
        require(isinstance(info,dict) and set(info)=={'dev','ino','uid','gid','mode','sha256'}
                and integer(info['dev']) and integer(info['ino'],1) and info['uid']==0 and info['gid']==0
                and info['mode']==(0o700 if name=='.' else 0o600))
        require(info['sha256']==(None if name=='.' else hashlib.sha256(lease_values[name]).hexdigest()))


def history_evidence(b, sha):
    if sha != FAILED_SHA:
        raise RecoveryError('unknown host recovery history')
    root=STATE/'host-hardening-recoveries'
    b.secure(root)
    if {p.name for p in root.iterdir()} != {sha}:
        raise RecoveryError('unknown host recovery inventory')
    record=root/sha
    b.secure(record)
    if {p.name for p in record.iterdir()} != {'intent.json','completed.json','apply','lease'}:
        raise RecoveryError('host recovery not complete')
    intent=b._read_json(record/'intent.json');completed=b._read_json(record/'completed.json')
    if (set(intent) != {'production_sha','publisher_sha','preserved','lease','frontend','legacy','services','cache','firewall','key_modes','permission_repair'}
            or re.fullmatch(r'[a-f0-9]{40}', str(intent.get('publisher_sha'))) is None
            or intent['publisher_sha'] == sha):
        raise RecoveryError('host recovery intent schema differs')
    expected={'state':'RECOVERED_LOCAL_VERIFIED','production_sha':sha,'publisher_sha':intent['publisher_sha'],
              'intent_sha256':digest(intent),'external_readback_required':True}
    if intent['production_sha'] != sha or completed != expected:
        raise RecoveryError('host recovery completion binding differs')
    preserved={'audit':b._inventory(STATE/sha/'host-hardening',AUDIT_NAMES),
               'backup':b._inventory(BACKUPS/sha,BACKUP_NAMES)}
    if preserved != intent['preserved']:
        raise RecoveryError('original host evidence changed')
    source=b.canonical_source(intent['publisher_sha'])
    source_scope(source,b.canonical_source(sha),None)
    b.secure(source/'scripts/harden_public_host.py')
    if os.path.lexists(source/'scripts/__pycache__'):
        raise RecoveryError('cached history code forbidden')
    import importlib.util
    spec=importlib.util.spec_from_file_location('history_host_guard',source/'scripts/harden_public_host.py')
    guard=importlib.util.module_from_spec(spec);spec.loader.exec_module(guard)
    if b._read_json(record/'apply/completed.json') != {'sha':sha,'status':'APPLIED'} or b._read_json(record/'apply/phase.json') != {'phase':'frontend_cutover'}:
        raise RecoveryError('host apply completion differs')
    b._inventory(record/'apply',{'phase.json','completed.json'})
    copied=b._inventory(record/'lease',{'token','label','stage','started_at'})
    verify_backup(BACKUPS/sha,guard,live=False)
    for name,state in (('started.json','STARTED'),('failed.json','NEEDS_OPERATOR')):
        if b._read_json(STATE/sha/'host-hardening'/name) != {'sha':sha,'state':state}:
            raise RecoveryError('historical host failure chain differs')
    validate_intent(intent,b._read_json(BACKUPS/sha/'intent.json'),b._read_json(STATE/sha/'host-hardening/frontend.json'),
                    {name:(record/'lease'/name).read_bytes() for name in ('token','label','stage','started_at')},guard)
    for name in ('token','label','stage','started_at'):
        if any(copied[name][field] != intent['lease'][name][field] for field in ('uid','gid','mode','sha256')):
            raise RecoveryError('host original lease archive differs')
    permission_root=STATE/'runtime-permission-repairs'/sha
    binding=intent['permission_repair']
    if binding is not None:
        repair_path=source/'scripts/runtime_permission_repair.py'
        b.secure(repair_path)
        spec=importlib.util.spec_from_file_location('permission_historical_proof',repair_path)
        repair=importlib.util.module_from_spec(spec);spec.loader.exec_module(repair)
        from types import SimpleNamespace
        adapter=SimpleNamespace(b=b,old=b.canonical_source(sha),guard=guard,backup=BACKUPS/sha,
            audit=STATE/sha/'host-hardening',preserved=lambda:preserved,lease=lambda:intent['lease'])
        old,new=repair.inspect_history(adapter,sys.modules[__name__],live=False,
            lease_values={name:(record/'lease'/name).read_bytes() for name in ('token','label','stage','started_at')})
        if binding!={'intent_sha256':digest(old),'completion_sha256':digest(new)} or intent['services']!=new['after_services']:
            raise RecoveryError('permission repair history binding differs')
    elif os.path.lexists(permission_root):
        raise RecoveryError('unbound permission repair history')
    return {'kind':'recovered-host-hardening','intent_sha256':digest(intent),'completion_sha256':digest(completed)}
