import Foundation

public enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case zh
    case en

    public static let defaultsKey = "appLanguage"
    public static let defaultLanguage = AppLanguage.zh

    public var id: String { rawValue }

    public var nativeName: String {
        switch self {
        case .zh: "中文"
        case .en: "English"
        }
    }

    public init(storedValue: String) {
        self = AppLanguage(rawValue: storedValue) ?? .defaultLanguage
    }
}

public enum L10n {
    public static func text(_ key: String, language: AppLanguage) -> String {
        switch language {
        case .zh:
            zhCN[key] ?? key
        case .en:
            key
        }
    }

    private static let zhCN: [String: String] = [
        "Health Agent": "健康 Agent",
        "Today": "今日",
        "Health": "健康",
        "Agent": "助手",
        "Record": "记录",
        "Data": "数据",
        "Genetics": "基因",
        "Knowledge": "知识库",
        "Labs, records, trajectory, and active medical imports.": "化验、记录、轨迹和进行中的医疗导入。",
        "Genome reanalysis jobs, source hashes, and risk-boundary handoff.": "基因重分析任务、来源哈希和风险边界交接。",
        "Dedao compilation, system KB rebuilds, and source coverage.": "得到资料编译、系统知识库重建和来源覆盖。",
        "Jobs": "任务",
        "Trace": "追踪",
        "Settings": "设置",
        "Command Palette": "命令面板",
        "Ask Agent": "问助手",
        "Import": "导入",
        "Increase Font Size": "放大字体",
        "Decrease Font Size": "缩小字体",
        "Reset Font Size": "重置字体大小",
        "Import File": "导入文件",
        "Reopen App": "重新打开 App",
        "Open Today": "打开今日",
        "Quit": "退出",
        "Checking login...": "正在检查登录状态...",
        "Sign in with your executor.life account.": "使用 executor.life 账号登录。",
        "Username or email": "用户名或邮箱",
        "Password": "密码",
        "Sign In": "登录",
        "Signing in...": "正在登录...",
        "Daily operating plan, feedback, and active desktop jobs.": "每日执行计划、反馈和桌面任务。",
        "Health Dashboard": "健康看板",
        "Loading your latest health context.": "正在加载你的最新健康上下文。",
        "Data date": "数据日期",
        "Active cards": "活跃卡片",
        "Memory": "记忆",
        "Diet 30d": "30天饮食",
        "Water 30d": "30天饮水",
        "Diet 7d": "7天饮食",
        "Water 7d": "7天饮水",
        "Supplements 7d": "7天补剂",
        "Supplements 30d": "30天补剂",
        "Diet Trend": "饮食趋势",
        "Water Trend": "饮水趋势",
        "Supplement Trend": "补剂趋势",
        "Nutrition & Intake": "饮食饮水",
        "Input Inbox": "输入收件箱",
        "Silent capture, review when needed.": "无感采集，需要时再审核。",
        "No input events loaded.": "还没有输入事件。",
        "Device": "设备",
        "Image": "图片",
        "Auto Saved": "已自动保存",
        "Needs Review": "待审核",
        "Confirmed": "已确认",
        "Needs Confirmation": "待确认",
        "Ignored": "已忽略",
        "Confirm Action": "确认动作",
        "Ignore": "忽略",
        "Structured command requires confirmation before execution.": "结构化命令执行前需要你确认。",
        "All": "全部",
        "Synced automatically. Ready for Agent context.": "已自动同步，可直接作为 Agent 上下文。",
        "Already saved. Use it as context or ask for follow-up.": "已入库，可加入上下文或继续追问。",
        "Import is still running. Review before relying on it.": "导入仍在运行，使用前需要复核。",
        "Import completed. Ready for knowledge or health context.": "导入已完成，可作为知识或健康上下文。",
        "7 days": "7天",
        "30 days": "30天",
        "days": "天",
        "Avg": "日均",
        "Average": "均值",
        "Record Count": "记录数",
        "Latest Record": "最近记录",
        "Trend Detail": "趋势详情",
        "Detailed Trend Chart": "详细趋势图",
        "Daily Points": "每日点位",
        "No trend points loaded.": "还没有趋势点位。",
        "Click to inspect trend": "点击查看趋势详情",
        "Add Trend Context": "加入趋势上下文",
        "Ask Agent about Trend": "让助手分析趋势",
        "/day": "/天",
        "Adherence": "依从率",
        "active": "启用",
        "Latest Weight": "最新体重",
        "Latest BP": "最新血压",
        "Steps": "步数",
        "Sleep Score": "睡眠评分",
        "SpO2": "血氧",
        "Resting HR": "静息心率",
        "Wearable Today": "今日穿戴",
        "Readiness": "训练准备度",
        "cards": "卡片",
        "memories": "记忆",
        "recent records": "最近记录",
        "records": "条记录",
        "No record": "暂无记录",
        "No wearable data": "暂无穿戴数据",
        "wearable": "穿戴数据",
        "Priority Actions": "优先行动",
        "Now do this": "现在做这件事",
        "Start": "开始",
        "Switch": "换一个",
        "Why this?": "为什么是这件事？",
        "Nothing on deck. Take a breath.": "暂时没有优先项。歇一会儿。",
        "Today's Briefing": "今日简报",
        "Nighttime SpO2": "夜间血氧",
        "Loading nightly SpO2...": "正在加载夜间血氧…",
        "No SpO2 data for last night.": "昨晚暂无血氧数据。",
        "Wear your Garmin during sleep to capture overnight SpO2.": "睡眠期间佩戴 Garmin 以采集夜间血氧。",
        "Lowest": "最低",
        "Below 90%": "低于 90% 占比",
        "Samples": "样本数",
        "Lowest episodes": "低值时刻",
        "Aligned overnight metrics": "夜间多指标对齐",
        "Heart rate": "心率",
        "Respiration": "呼吸频率",
        "HRV": "心率变异",
        "Stress": "压力",
        "Sleep stages": "睡眠分期",
        "Deep": "深睡",
        "Light": "浅睡",
        "REM": "REM",
        "Awake": "清醒",
        "Min": "最低",
        "Max": "最高",
        "d": "天",
        "Sneeze": "打喷嚏",
        "Sneeze count today": "今日打喷嚏次数",
        "Nasal Wash": "洗鼻",
        "Nasal wash count today": "今日洗鼻次数",
        "Exercise type": "运动类型(如 俯卧撑)",
        "Reps": "次数",
        "Sets": "组数",
        "Duration min": "时长(分钟)",
        "Common reps · one tap to fill": "常用次数 · 点一下填入",
        "reps/min": "次/分钟",
        "times": "次",
        "Vitals & Sleep": "生理与睡眠",
        "Vitals & Sleep Trends": "生理与睡眠趋势",
        "Sleep Stages": "睡眠分期",
        "Avg HR": "平均心率",
        "Body Battery": "身体电量",
        "Sleep": "睡眠",
        "low": "最低",
        "score": "评分",
        "Last 7 nights SpO2": "近 7 夜血氧",
        "No SpO2 history available.": "暂无血氧历史数据。",
        "Lab indicator trends": "化验指标趋势",
        "No lab indicator data yet.": "还没有化验指标数据。",
        "Import a medical exam PDF or photo to start tracking.": "导入体检 PDF 或拍照上传后即可追踪。",
        "Reference": "参考",
        "Latest": "最近",
        "First": "首次",
        "Visits": "次数",
        "Abnormal": "异常",
        "Ask Agent about this": "请教 Agent",
        "Add to context": "加入上下文",
        "Initial": "初始",
        "step": "步",
        "steps": "步",
        "Deeper": "深入这一点",
        "Action steps": "给执行步骤",
        "Plain words": "翻译成大白话",
        "Find evidence": "找证据",
        "Compare last": "对比上次",
        "Recent Health Records": "最近健康记录",
        "No recent health records loaded.": "还没有加载最近健康记录。",
        "Refresh": "刷新",
        "Loading desktop context...": "正在加载桌面上下文...",
        "Top Actions": "优先行动",
        "No actions loaded yet.": "还没有加载行动。",
        "Done": "完成",
        "Adjust": "调整",
        "Status Center": "状态中心",
        "Cards": "卡片",
        "Active Jobs": "进行中的任务",
        "Active": "活跃",
        "No active desktop jobs.": "没有进行中的桌面任务。",
        "Loading workspace...": "正在加载工作台...",
        "No workspace data loaded": "还没有工作台数据",
        "Open Agent": "问助手",
        "Open Record": "打开记录",
        "Open Data": "打开数据",
        "Open Genetics": "打开基因",
        "Open Knowledge": "打开知识库",
        "Open Jobs": "打开任务",
        "Open Settings": "打开设置",
        "Ask Agent with Current Context": "基于当前上下文问助手",
        "Open Agent with the selected context basket.": "打开助手，并保留当前已选上下文。",
        "Refresh Desktop Data": "刷新桌面数据",
        "Reload dashboard, records, genes, knowledge, and jobs.": "重新加载看板、记录、基因、知识库和任务。",
        "New Conversation": "新对话",
        "Start a fresh agent conversation with empty context.": "开启一个全新的助手对话，上下文清空。",
        "Open Quick Record": "打开快速记录",
        "Recommended next step": "建议的下一步",
        "Open in Agent": "用助手打开",
        "Jump to record to log diet, water, supplement, or vitals.": "跳到记录页，登记饮食、饮水、补剂或生命体征。",
        "Why am I tired today?": "我今天为什么累？",
        "Ask the agent to analyze readiness, sleep, and load.": "让助手分析 readiness、睡眠和训练负荷。",
        "Should I train today?": "今天该不该练？",
        "Ask the agent to weigh recovery against training load.": "让助手在 readiness 和训练量之间权衡。",
        "Summarize my latest labs": "总结我最近的化验",
        "Ask the agent to summarize most-recent lab results.": "让助手总结最近一次化验的偏离项。",
        "What should I eat today?": "今天吃什么？",
        "Ask the agent for a nutrition plan tailored to today.": "让助手按今天状态给三餐和加餐建议。",
        "Search command or action": "搜索命令或动作",
        "Run first result": "执行第一条结果",
        "Daily dashboard, priorities, and recent context.": "每日看板、优先事项和近期上下文。",
        "Ask questions with files, selected context, and evidence.": "结合文件、已选上下文和证据发问。",
        "Record diet, water, supplements, vitals, and symptoms.": "记录饮食、饮水、补剂、体征和症状。",
        "Inspect records, trends, labs, and wearable summaries.": "查看记录、趋势、化验和穿戴摘要。",
        "Review genome findings, risk boundaries, and imports.": "查看基因发现、风险边界和导入。",
        "Review source coverage, claims, and evidence.": "查看来源覆盖、claims 和证据。",
        "Inspect import, reanalysis, and rebuild jobs.": "查看导入、重分析和重建任务。",
        "Inspect Agent model, tool, source, and timing traces.": "查看 Agent 模型、工具、来源和耗时追踪。",
        "Manage login, API, language, voice, and privacy.": "管理登录、API、语言、语音和隐私。",
        "Focus Domains": "关注领域",
        "Workspace Actions": "工作台行动",
        "No focus domains loaded.": "还没有关注领域。",
        "Relevant Jobs": "相关任务",
        "No active jobs for this workspace.": "这个工作台没有进行中的任务。",
        "Recent Memory": "近期记忆",
        "History": "历史",
        "Continue a recent conversation or start fresh.": "继续最近对话，或开始新对话。",
        "New Chat": "新对话",
        "Load Chat": "载入对话",
        "messages": "条消息",
        "No recent memory loaded.": "还没有近期记忆。",
        "No actions loaded": "还没有行动",
        "Analysis": "分析",
        "Turn health context into an answer, plan, or evidence check.": "把健康上下文变成回答、计划或证据检查。",
        "New Analysis": "新分析",
        "Draft, attach, then run.": "先写问题，补充上下文，再运行。",
        "Title": "标题",
        "Attach": "添加附件",
        "Web Search": "联网搜索",
        "Ready": "就绪",
        "Preparing": "准备中",
        "Generating": "生成中",
        "Completed": "已完成",
        "Partial": "部分完成",
        "Failed": "失败",
        "Succeeded": "成功",
        "Tool Timeline": "工具执行",
        "View Tool Result": "查看工具结果",
        "Arguments": "调用参数",
        "Tool Result": "执行结果",
        "Round": "轮次",
        "Close": "关闭",
        "No arguments captured.": "没有捕获到调用参数。",
        "No tool result yet.": "还没有工具执行结果。",
        "Running": "运行中",
        "Run": "运行",
        "Something went wrong. Please try again.": "出了点问题，请稍后再试。",
        "Copy": "复制",
        "Copied": "已复制",
        "Stop": "停止",
        "Stop generating": "停止生成",
        "Ask about health data, labs, genes, records, or a specific execution plan.": "询问健康数据、化验、基因、记录或具体执行方案。",
        "Analyze my latest health records and give today priorities.": "分析我最近的健康记录，给出今天的优先事项。",
        "Create a 30-day plan based on genes, labs, supplements, and exercise.": "结合基因、化验、补剂和运动，制定 30 天执行方案。",
        "Check this answer for evidence and uncertainty boundaries.": "检查这份回答的证据和不确定性边界。",
        "Models": "模型",
        "Model Routing": "模型路由",
        "Mode": "模式",
        "Auto Select": "自动选择",
        "Default 3": "默认 3 个",
        "Manual": "手动",
        "Auto": "自动",
        "Currently using": "当前使用",
        "Let the backend choose the best route.": "让后端自动选择最合适的路由。",
        "Use the default 3-model panel.": "使用默认 3 模型面板。",
        "Evidence": "证据",
        "Context": "上下文",
        "Selected Context": "已选上下文",
        "Add Context": "加入上下文",
        "Saved Context Bundles": "已保存上下文包",
        "Bundle name": "上下文包名称",
        "Save Bundle": "保存上下文包",
        "Apply Bundle": "应用上下文包",
        "items": "项",
        "Files": "文件",
        "Web": "联网",
        "Route": "路由",
        "On": "开启",
        "Off": "关闭",
        "Drag files here or use Attach.": "可拖入文件，也可用添加附件。",
        "Use for current facts and external sources.": "用于当前事实和外部来源。",
        "Sources, attachments, and evidence refs will appear here.": "来源、附件和证据引用会显示在这里。",
        "Attachments": "附件",
        "Sources": "来源",
        "Items waiting in the context basket.": "上下文篮里待发送的项。",
        "Evidence: High": "高证据",
        "Evidence: Medium": "中证据",
        "Evidence: Low": "弱证据",
        "Evidence: Medical": "医学级",
        "You": "你",
        "Assistant": "助手",
        "Run an analysis to see the answer stream here.": "运行一次分析后，回答流会显示在这里。",
        "Sources, model, and file context stay visible while you iterate.": "迭代时来源、模型和文件上下文会保持可见。",
        "Ready for desktop chat, file context, and evidence inspection.": "已准备好桌面聊天、文件上下文和证据检查。",
        "Quick Record": "快捷记录",
        "Capture food, water, supplements, vitals, and symptoms without leaving the keyboard.": "不用离开键盘，快速记录饮食、饮水、补剂、体征和症状。",
        "Natural Language": "自然语言",
        "Best for fast food, water, supplement, or symptom notes.": "适合快速记录饮食、饮水、补剂或症状。",
        "Example: dinner had half rice, beef, broccoli; drank 500ml water": "例如：晚餐半碗米饭、牛肉、西兰花；喝水 500ml",
        "Drank 500ml water": "喝水 500ml",
        "Took fish oil after dinner": "晚饭后吃了鱼油",
        "Weight 70.2kg this morning": "今早体重 70.2kg",
        "Blood pressure 119/75": "血压 119/75",
        "Save Natural": "保存自然语言记录",
        "Clear": "清空",
        "Quick parser will infer record type.": "快速解析会自动推断记录类型。",
        "Structured Form": "结构化表单",
        "Use when values must be precise.": "需要精确数值时使用。",
        "Use Preview": "使用预览",
        "Typed endpoint, audit-friendly.": "走类型化接口，便于审计。",
        "Current Draft": "当前草稿",
        "Structured Preview": "结构化预览",
        "Fill structured fields to preview the saved record.": "填写结构化字段后，会预览将要保存的记录。",
        "Saved results and undo controls will appear here.": "保存结果和撤销入口会显示在这里。",
        "Record food, water, supplement, weight, BP, or symptom": "记录饮食、饮水、补剂、体重、血压或症状",
        "Type": "类型",
        "Diet": "饮食",
        "Water": "饮水",
        "Weight": "体重",
        "BP": "血压",
        "Symptom": "症状",
        "Preview": "预览",
        "Save Structured": "保存结构化记录",
        "Saving...": "正在保存...",
        "Save": "保存",
        "Recent Local Records": "本地最近记录",
        "Recent saved commands in this Mac session will appear here.": "本次 Mac 会话保存过的记录命令会显示在这里。",
        "Recent Record Snapshot": "近期记录快照",
        "Latest day": "最近一天",
        "Average and trend baseline": "均值与趋势基线",
        "Today Diet": "今日饮食",
        "Today Water": "今日饮水",
        "Today Supplements": "今日补剂",
        "Latest Vitals": "最新体征",
        "Saved": "已保存",
        "Undo": "撤销",
        "Undoing...": "正在撤销...",
        "Undo failed": "撤销失败",
        "Record undone.": "记录已撤销。",
        "Reuse": "复用",
        "Delete": "删除",
        "Food name or photo description": "食物名称或图片描述",
        "Calories kcal": "热量 kcal",
        "Protein g": "蛋白质 g",
        "Amount ml": "饮水量 ml",
        "Frequent · one tap to log": "常喝 · 点一下直接记录",
        "Frequent · one tap to check in": "常吃补剂 · 点一下打卡",
        "Supplement": "补剂",
        "Dose and timing": "剂量和时间",
        "Choose from Supplement Library": "从补剂库选择",
        "Linked Product": "已关联产品",
        "Search brand or product name": "搜索品牌或产品名",
        "Searching supplement library...": "正在搜索补剂库...",
        "Enter a product keyword first.": "先输入产品关键词。",
        "No matching products. You can still enter manually.": "未找到匹配产品，仍可手动输入。",
        "products found": "个产品",
        "Search failed": "搜索失败",
        "vitamin": "维生素",
        "mineral": "矿物质",
        "antioxidant": "抗氧化",
        "amino": "氨基酸",
        "herb": "草本",
        "other": "其他",
        "Weight kg": "体重 kg",
        "Systolic": "收缩压",
        "Diastolic": "舒张压",
        "Symptom, severity, and context": "症状、严重程度和背景",
        "food": "食物",
        "ml": "毫升",
        "dose": "剂量",
        "kg": "kg",
        "mmHg": "mmHg",
        "context": "背景",
        "Choose File or Folder": "选择文件或文件夹",
        "Create Job": "创建任务",
        "Detected Route": "识别路由",
        "Review hash and route before creating a long-running desktop job.": "创建长任务前先确认哈希和路由。",
        "I confirm this raw local file may be registered as a desktop import job.": "我确认可以将这个本地原始文件登记为桌面导入任务。",
        "No file selected": "还没有选择文件",
        "Select a genome txt, medical file, Apple Health export, or Dedao folder.": "选择基因 txt、医疗文件、Apple Health 导出或得到文件夹。",
        "ID": "ID",
        "Progress": "进度",
        "Total": "总数",
        "Action": "操作",
        "Details": "详情",
        "Retry": "重试",
        "Job Detail": "任务详情",
        "Job completed": "任务已完成",
        "Job failed": "任务失败",
        "Job still running": "任务运行中",
        "Job status unknown": "任务状态未知",
        "Next Actions": "下一步",
        "Review generated results": "查看生成结果",
        "Add results to Agent context": "加入 Agent 上下文",
        "Open trace": "打开追踪",
        "Review error": "查看错误",
        "Check source hash": "检查来源哈希",
        "Retry job": "重试任务",
        "Wait for completion": "等待完成",
        "Review source context": "查看来源上下文",
        "Review raw result": "查看原始结果",
        "Action cards": "行动卡片",
        "Imported records": "导入记录",
        "Findings": "发现",
        "Source hash": "来源哈希",
        "results are ready. Review before using them as Agent context.": "结果已就绪。加入 Agent 上下文前请先复核。",
        "complete. Return here from the menu bar when it finishes.": "完成。结束后可从菜单栏回到这里复核。",
        "Inspect the raw result before acting on it.": "采取行动前请先检查原始结果。",
        "No pending job results.": "没有待处理的任务结果。",
        "Status": "状态",
        "Source": "来源",
        "Metric": "指标",
        "Kind": "类型",
        "Open Trace": "打开追踪",
        "Result": "结果",
        "Select a job to inspect source, result, error, and trace handoff.": "选择一个任务以查看来源、结果、错误和追踪跳转。",
        "Conversation ID": "对话 ID",
        "Load": "加载",
        "Conversation": "对话",
        "Model": "模型",
        "Elapsed": "总耗时",
        "LLM": "LLM",
        "Finish": "结束原因",
        "No trace loaded": "还没有加载追踪",
        "No desktop jobs yet": "还没有桌面任务",
        "Create import or reanalysis jobs from Data, Genetics, or Knowledge tabs.": "可以从数据、基因或知识库页面创建导入和重分析任务。",
        "Health Actions": "健康行动",
        "No desktop jobs match this filter.": "没有符合当前筛选的桌面任务。",
        "Health action cards are still shown above for follow-up.": "上方仍会显示需要跟进的健康行动卡片。",
        "Auth": "认证",
        "Bearer token": "Bearer token",
        "Save Token": "保存 Token",
        "Clear Token": "清除 Token",
        "Sign Out": "退出登录",
        "Signed in as": "当前登录",
        "Switch Account": "切换账户",
        "Sign out and return to the login screen.": "退出登录并返回登录界面。",
        "Sign out of this account?": "确定退出当前账户？",
        "Open Settings to switch account.": "前往设置可切换账户。",
        "Notifications": "通知",
        "Enable safety alerts": "开启安全告警",
        "Play alert sound": "播放提示音",
        "Minimum alert level": "最低告警级别",
        "Medium and above": "中风险及以上",
        "High and above": "高风险及以上",
        "Critical only": "仅紧急",
        "Check frequency": "检查频率",
        "Enable/level/sound apply immediately; frequency takes effect after restarting the Mac app.": "开关/级别/提示音立即生效；检查频率重启 Mac App 后生效。",
        "Startup": "启动",
        "Launch at login": "登录时自动启动",
        "Launch at login change failed": "设置开机自启失败",
        "Workouts": "运动",
        "Recent training and load.": "近期训练与负荷。",
        "Recent Workouts": "近期运动",
        "No workouts loaded yet.": "暂无运动记录。",
        "Could not load workouts. Pull to refresh.": "运动记录加载失败，点击刷新重试。",
        "Last": "近",
        "Total minutes": "总时长(分钟)",
        "Calories": "热量",
        "Distance (km)": "距离(km)",
        "Weekly frequency": "每周频次",
        "min": "分钟",
        "Cycling": "骑行",
        "Swimming": "游泳",
        "Strength": "力量",
        "Yoga": "瑜伽",
        "Walking": "步行",
        "HIIT": "高强度间歇",
        "Workout": "运动",
        "Goals": "目标",
        "Health goals and progress.": "健康目标与进度。",
        "Overview": "概览",
        "Completion rate": "完成率",
        "Your Goals": "我的目标",
        "No goals loaded yet.": "暂无目标。",
        "Paused": "已暂停",
        "Abandoned": "已放弃",
        "API": "API",
        "Base URL": "Base URL",
        "Changing the API base URL takes effect after restarting the Mac app.": "修改 API 地址后，重启 Mac App 生效。",
        "Voice": "语音",
        "Output voice": "输出音色",
        "Private Female": "私享女声",
        "System Default": "系统默认",
        "Privacy and Files": "隐私和文件",
        "Allow local file hashing before import": "导入前允许本地文件哈希",
        "Files stay local in this P0 client. Import jobs register source metadata and hashes unless a backend upload flow is added later.": "P0 客户端中文件保持在本地。除非后续增加后端上传流程，导入任务只登记来源元数据和哈希。",
        "Language": "语言",
        "Display language": "显示语言",
        "Chinese is the default. Language changes apply immediately in most views.": "默认使用中文。大多数界面会立即应用语言切换。",
        "Gene Jobs": "基因任务",
        "KB Jobs": "知识库任务",
        "Variants": "位点",
        "Active Variants": "当前报告位点",
        "All Variants": "全部位点",
        "Profiles": "报告",
        "High Risk": "高风险",
        "Medium Risk": "中风险",
        "High": "高",
        "Medium": "中",
        "Categories": "分类",
        "variants": "个位点",
        "disease_risk": "疾病风险",
        "nutrition": "营养代谢",
        "drug_sensitivity": "药物敏感性",
        "cognition": "认知",
        "exercise": "运动",
        "sleep": "睡眠",
        "height_trait": "身高/体征",
        "recovery": "恢复",
        "trait": "性状",
        "carrier_status": "携带状态",
        "ancestry": "祖源",
        "pharmacogenomics": "药物基因组",
        "Documents": "文档",
        "Claims": "结论",
        "Articles": "文章",
        "Entities": "实体",
        "Entity Types": "实体类型",
        "Edges": "关系",
        "Action Cards": "行动卡片",
        "Refresh recent health data": "刷新近期健康数据",
        "Update labs, records, wearable trajectory, and medical imports before analysis.": "分析前更新化验、记录、穿戴轨迹和医疗导入。",
        "Review weekly intake": "复盘七天摄入",
        "Use the 7-day diet, water, and supplement baseline before making daily decisions.": "先用 7 天饮食、饮水和补剂基线，再做当天决策。",
        "Create medical import": "创建医疗导入",
        "Register lab PDFs or Apple Health exports as auditable desktop jobs.": "把化验 PDF 或 Apple Health 导出登记为可审计桌面任务。",
        "Health Data Command Center": "健康数据指挥台",
        "Range": "范围",
        "Trends": "趋势",
        "Import genome file": "导入基因文件",
        "Drop WeGene, 23andMe, or other raw genotype txt files to create a reanalysis job.": "拖入 WeGene、23andMe 或其他原始 genotype txt，创建重分析任务。",
        "Run risk reanalysis": "执行风险重分析",
        "Rebuild risk calls with source hashes, confidence, and uncertainty boundaries.": "用来源哈希、置信度和不确定性边界重建风险结论。",
        "Keep clinical boundary": "保留临床边界",
        "Treat genetic results as risk stratification, not diagnosis or medication decisions.": "基因结果只用于风险分层，不作为诊断或用药决策。",
        "Import Dedao folder": "导入得到目录",
        "Use the local down-dedao health courses and ebooks as source material.": "使用本地 down-dedao 健康课程和电子书作为来源材料。",
        "Rebuild system KB": "重建系统知识库",
        "Compile claims, evidence refs, and source coverage for safer Agent answers.": "编译 claim、证据引用和来源覆盖，让 Agent 回答更可靠。",
        "Audit source coverage": "审查来源覆盖",
        "Check whether answers cite enough dedao, pubmed, and system evidence.": "检查回答是否引用了足够的得到、PubMed 和系统证据。",
        "Create Import Job": "创建导入任务",
        "Create Rebuild Job": "创建重建任务",
        "Created desktop job": "已创建桌面任务",
        "Recent health data refreshed.": "近期健康数据已刷新。",
        "Opened a fresh Agent draft with this workspace context.": "已用当前工作台上下文打开新助手草稿。",
        "Action failed": "操作失败",
        "Genetic Risk Summary": "基因风险摘要",
        "Genetic Import Coverage": "基因导入覆盖",
        "Genetic Profiles": "基因报告",
        "Genetic Finding Detail": "基因发现详情",
        "Genetic Category Detail": "基因分类详情",
        "View Detail": "查看详情",
        "Detail": "详情",
        "Ask": "提问",
        "Add": "加入",
        "Ask Agent with Context": "带上下文问助手",
        "Interpretation": "解读",
        "No description loaded.": "还没有加载描述。",
        "Genetic results are for risk stratification, not diagnosis or medication decisions.": "基因结果只用于风险分层，不作为诊断或用药决策。",
        "Representative Findings": "代表性发现",
        "No representative findings loaded for this category.": "这个分类还没有加载代表性发现。",
        "Ask the Agent to combine this category with labs, symptoms, supplements, and exercise data.": "让助手把这个分类与化验、症状、补剂和运动数据结合分析。",
        "Gene": "基因",
        "Genotype": "基因型",
        "Category": "分类",
        "Nature": "性质",
        "Raw": "原始位点",
        "Coverage": "覆盖率",
        "Matched": "已匹配",
        "Unmapped": "未映射",
        "Missing": "缺失",
        "Top Genetic Findings": "重点基因发现",
        "No genetic variants loaded yet.": "还没有加载基因位点。",
        "No high-signal genetic findings loaded.": "还没有加载高信号基因发现。",
        "Knowledge Coverage": "知识库覆盖",
        "Knowledge Workbench": "知识库工作台",
        "Knowledge Documents": "知识文档",
        "Source Coverage": "来源覆盖",
        "Search": "搜索",
        "Search knowledge documents": "搜索知识文档",
        "No matching knowledge documents": "没有匹配的知识文档",
        "Try another keyword or document type.": "换一个关键词或文档类型试试。",
        "No data loaded yet.": "还没有加载数据。",
        "Level": "等级",
        "Document Types": "文档类型",
        "Entity Coverage": "实体覆盖",
        "Local LLM Wiki Source": "本地 LLM Wiki 来源",
        "Connected": "已连接",
        "Not Found": "未找到",
        "Wiki Markdown": "Wiki 文档",
        "Artifacts JSON": "编译产物",
        "Raw Sources": "原始素材",
        "Linked KB Docs": "已入库文档",
        "Compiled": "编译时间",
        "article": "文章",
        "claim": "结论",
        "entity": "实体",
        "protocol": "方案",
        "intervention": "干预",
        "gene": "基因",
        "condition": "疾病/状态",
        "drug": "药物",
        "biomarker": "指标",
        "course": "课程",
        "snp": "SNP",
        "concept": "概念",
        "Recent Knowledge Documents": "近期知识文档",
        "Knowledge Document Detail": "知识文档详情",
        "Document ID": "文档 ID",
        "Confidence": "置信度",
        "Summary": "摘要",
        "No source refs loaded.": "还没有来源引用。",
        "Use this source with your own data before turning it into an action.": "先结合你的真实数据，再把这条资料转成行动。",
        "Clinical Boundary": "临床边界",
        "Use genotype as a risk flag, not a diagnosis.": "基因型只作为风险提示，不作为诊断。",
        "Confirm high-impact findings with clinical testing before medication or disease decisions.": "涉及用药或疾病决策前，先用临床检测确认高影响发现。",
        "Ask Agent with recent labs, symptoms, supplements, and exercise before changing plans.": "调整计划前，结合近期化验、症状、补剂和运动数据问 Agent。",
        "Quick Capture": "快速记录",
        "Record Water 200ml": "记录饮水 200ml",
        "Record Supplements Taken": "记录补剂已吃",
        "Save failed": "保存失败",
        "Symptom, measurement, note...": "症状、测量值、备注…",
        "Cancel": "取消",
        "Saved.": "已保存。",
        "Medication started": "用药开始",
        "Supplement started": "补剂开始",
        "Overnight SpO2 risk · last 7 nights": "夜间 SpO2 风险 · 最近 7 夜",
        "Overnight SpO2 looks steady this week.": "本周夜间 SpO2 看起来稳定。",
        "%d night(s) with sustained low-SpO2 segments.": "有 %d 夜出现持续低氧段。",
        "%d nights showed sustained low-SpO2 segments — consider follow-up.": "有 %d 夜持续出现低氧段，建议复查或就医评估。",
        "Remind me": "提醒我",
        "Add to basket": "加入上下文",
        "Reminder set": "已设提醒",
        "No knowledge documents loaded yet.": "还没有加载知识文档。"
    ]
}
